In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import psignifit as pf
from tqdm import tqdm
from scipy.stats import gamma, lognorm, norm

from psychoanalyze import data
from datetime import datetime

pd.set_option('io.hdf.default_format','table')

In [15]:
points = data.load('points').drop(data.outliers['points'])
curves = data.load('curves')
# sessions = pd.read_csv('../data/1-normalized/sessions.csv', parse_dates=['Date'])
# monkeys = pd.read_csv('../data/1-normalized/subjects.csv', parse_dates=['Date of Implant Surgery'])

In [3]:
curve_columns = ['Monkey','Date','Ref Amp','Ref PW', 'Ref Freq','Ref Dur', 'Active Channels','Return Channels']
curve_calculated_columns = ['FAs','CRs','Return Channel(s)','Channel(s)','n_catch','X dimension',
                            'base', 'location','width','lambda','gamma','beta',
                            'location_CI_95', 'width_CI_95', 'lambda_CI_95', 'gamma_CI_95', 'beta_CI_95',
                            'location_CI_5', 'width_CI_5', 'lambda_CI_5', 'gamma_CI_5', 'beta_CI_5']
point_columns = ['Comp Amp','Comp PW']

In [4]:
curves = points.groupby(curve_columns)[['FAs','CRs']].sum().reset_index()

In [5]:
points = points.drop(columns=['FAs','CRs'])

In [6]:
sessions_monkeys = sessions.merge(monkeys[['Monkey', 'Date of Implant Surgery']])
sessions['Days'] = (sessions_monkeys['Date'] - sessions_monkeys['Date of Implant Surgery']).dt.days

In [7]:
curves = data.channelint2mask(curves)
curves = data.channelmask2num(curves)

In [8]:
points['n'] = points['Hits'] + points['Misses']
curves['n_catch'] = curves['FAs'] + curves['CRs']
curves['FA_rate'] = curves['FAs'] / curves['n_catch']
points['HR'] = points['Hits'] / points['n']

In [9]:
curves.loc[(curves['Ref Amp'] < 2) | (curves['Ref PW'] < 2), 'Experiment Type'] = 'Detection'
curves.loc[(curves['Ref Amp'] >= 2) & (curves['Ref PW'] >= 2), 'Experiment Type'] = 'Discrimination'

In [10]:
def find_x_dim(df):
    n_Amp = df['Comp Amp'].nunique()
    n_PW = df['Comp PW'].nunique()
    if n_Amp > n_PW:
        df['X Dimension'] = 'Amp'
    elif n_Amp < n_PW:
        df['X Dimension'] = 'PW'
    elif (n_Amp < 3) & (n_PW < 3):
        df['X Dimension'] = 'None'
    else:
        df['X Dimension'] = 'Both'
    return df[curve_columns + ['X Dimension']]
    
curves_dim = points.groupby(curve_columns).apply(find_x_dim).drop_duplicates()
curves = curves.merge(curves_dim)

In [11]:
curves

,Monkey,Date,Ref Amp,Ref PW,Ref Freq,Ref Dur,Active Channels,Return Channels,FAs,CRs,Act Chan Mask,Ret Chan Mask,Return Channel(s),Channel(s),n_catch,FA_rate,Experiment Type,X Dimension
0,U,20160926,0,0,0,0,8,128,8,189,00001000,10000000,1,5,197,0.040609,Detection,Amp
1,U,20160927,0,0,0,0,9,144,37,191,00001001,10010000,1+4,5+8,228,0.162281,Detection,Amp
2,U,20160928,0,0,0,0,8,128,37,201,00001000,10000000,1,5,238,0.155462,Detection,Amp
3,U,20160929,0,0,0,0,15,128,83,246,00001111,10000000,1,5+6+7+8,329,0.252280,Detection,Amp
4,U,20161003,0,0,0,0,15,64,11,295,00001111,01000000,2,5+6+7+8,306,0.035948,Detection,Amp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076,Z,20170120,0,0,0,0,15,0,0,0,00001111,00000000,,5+6+7+8,0,NaN,Detection,None
1077,Z,20170120,0,0,0,0,15,16,21,113,00001111,00010000,4,5+6+7+8,134,0.156716,Detection,Amp
1078,Z,20170120,0,0,0,0,15,32,18,339,00001111,00100000,3,5+6+7+8,357,0.050420,Detection,Amp
1079,Z,20170120,0,0,0,0,15,64,5,129,00001111,01000000,2,5+6+7+8,134,0.037313,Detection,Amp
1080,Z,20170120,0,0,0,0,15,128,15,222,00001111,10000000,1,5+6+7+8,237,0.063291,Detection,Amp

In [12]:
curves = curves[curves['X Dimension'].isin(['Amp','PW'])]

In [6]:
curves_points = curves.merge(points, left_index=True, right_index=True)

In [21]:
curves_points['x'] = curves_points['Comp PW'].where(curves_points['X Dimension'] == 'PW', other=curves_points['Comp Amp'])
curves_points['base'] = curves_points['Ref Amp'].where(curves_points['X Dimension'] == 'PW', other=curves_points['Ref PW'])

In [22]:
points_x = curves_points[curve_columns + point_columns + ['x','base']]
points = points.merge(points_x)
# points.to_csv('../data/2-calculated/points.csv', index=False)

In [25]:
points

,Monkey,Date,Ref Amp,Ref PW,Ref Freq,Ref Dur,Active Channels,Return Channels,Comp Amp,Comp PW,Misses,Hits,n,x,base
0,U,20160926,0,0,0,0,8,128,1,1,0,0,0,1.0,1.0
1,U,20160926,0,0,0,0,8,128,75,200,0,1,1,75.0,200.0
2,U,20160926,0,0,0,0,8,128,350,200,1,1,2,350.0,200.0
3,U,20160926,0,0,0,0,8,128,492,200,0,1,1,492.0,200.0
4,U,20160926,0,0,0,0,8,128,1000,200,3,6,9,1000.0,200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9457,Z,20170120,0,0,0,0,15,128,90,200,0,10,10,90.0,200.0
9458,Z,20170120,0,0,0,0,15,128,110,200,0,12,12,110.0,200.0
9459,Z,20170120,0,0,0,0,15,128,130,200,0,12,12,130.0,200.0
9460,Z,20170120,0,0,0,0,15,128,150,200,0,11,11,150.0,200.0
9461,Z,20170120,0,0,0,0,15,128,170,200,0,11,11,170.0,200.0

In [27]:
points = points[points['n'] > 3]
# points.to_csv('../data/2-calculated/points.csv', index=False)

In [28]:
curves_points = points.merge(curves)
curves_points

,Monkey,Date,Ref Amp,Ref PW,Ref Freq,Ref Dur,Active Channels,Return Channels,Comp Amp,Comp PW,...,base,FAs,CRs,Act Chan Mask,Ret Chan Mask,Return Channel(s),Channel(s),n_catch,FA_rate,X dimension
0,U,20160926,0,0,0,0,8,128,1000,200,...,200.0,8,189,00001000,10000000,1,5,197,0.040609,Amp
1,U,20160926,0,0,0,0,8,128,1071,200,...,200.0,8,189,00001000,10000000,1,5,197,0.040609,Amp
2,U,20160926,0,0,0,0,8,128,1142,200,...,200.0,8,189,00001000,10000000,1,5,197,0.040609,Amp
3,U,20160926,0,0,0,0,8,128,1214,200,...,200.0,8,189,00001000,10000000,1,5,197,0.040609,Amp
4,U,20160926,0,0,0,0,8,128,1285,200,...,200.0,8,189,00001000,10000000,1,5,197,0.040609,Amp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8068,Z,20170120,0,0,0,0,15,128,90,200,...,200.0,15,222,00001111,10000000,1,5+6+7+8,237,0.063291,Amp
8069,Z,20170120,0,0,0,0,15,128,110,200,...,200.0,15,222,00001111,10000000,1,5+6+7+8,237,0.063291,Amp
8070,Z,20170120,0,0,0,0,15,128,130,200,...,200.0,15,222,00001111,10000000,1,5+6+7+8,237,0.063291,Amp
8071,Z,20170120,0,0,0,0,15,128,150,200,...,200.0,15,222,00001111,10000000,1,5+6+7+8,237,0.063291,Amp
8072,Z,20170120,0,0,0,0,15,128,170,200,...,200.0,15,222,00001111,10000000,1,5+6+7+8,237,0.063291,Amp

In [30]:
tqdm.pandas()
fitted_curves = curves_points.groupby(curve_columns + ['base']).progress_apply(fit_curve)

  0%|          | 0/993 [00:00<?, ?it/s]

(array([], dtype=int64),)

  0%|          | 2/993 [00:39<5:22:42, 19.54s/it]

(array([], dtype=int64),)

  0%|          | 3/993 [00:58<5:19:49, 19.38s/it]

(array([], dtype=int64),)

  0%|          | 4/993 [01:20<5:33:01, 20.20s/it]

(array([], dtype=int64),)

  1%|          | 5/993 [01:40<5:33:37, 20.26s/it]

(array([], dtype=int64),)

  1%|          | 6/993 [01:59<5:25:42, 19.80s/it]

(array([], dtype=int64),)

  1%|          | 7/993 [02:16<5:12:07, 18.99s/it]

(array([], dtype=int64),)

  1%|          | 8/993 [02:34<5:07:53, 18.75s/it]

(array([], dtype=int64),)

  1%|          | 9/993 [02:51<4:56:18, 18.07s/it]

(array([], dtype=int64),)

  1%|          | 11/993 [03:08<4:10:49, 15.33s/it]

(array([], dtype=int64),)

  1%|          | 12/993 [03:27<4:28:24, 16.42s/it]

(array([], dtype=int64),)

  1%|▏         | 13/993 [03:45<4:31:32, 16.63s/it]

(array([], dtype=int64),)

  1%|▏         | 14/993 [04:03<4:42:19, 17.30s/it]

(array([], dtype=int64),)

  2%|▏         | 15/993 [04:21<4:42:22, 17.32s/it]

(array([], dtype=int64),)

  2%|▏         | 16/993 [04:38<4:39:40, 17.18s/it]

(array([], dtype=int64),)

  2%|▏         | 17/993 [04:56<4:45:46, 17.57s/it]

(array([], dtype=int64),)

  2%|▏         | 18/993 [05:13<4:42:05, 17.36s/it]

(array([], dtype=int64),)

  2%|▏         | 19/993 [05:32<4:49:52, 17.86s/it]

(array([], dtype=int64),)

  2%|▏         | 20/993 [05:49<4:45:15, 17.59s/it]

(array([], dtype=int64),)

  2%|▏         | 21/993 [06:04<4:34:28, 16.94s/it]

(array([], dtype=int64),)

  2%|▏         | 22/993 [06:20<4:29:01, 16.62s/it]

(array([], dtype=int64),)

  2%|▏         | 24/993 [06:48<4:16:01, 15.85s/it]

(array([], dtype=int64),)

  3%|▎         | 27/993 [07:04<3:24:26, 12.70s/it]

(array([], dtype=int64),)

  3%|▎         | 28/993 [07:20<3:38:52, 13.61s/it]

(array([], dtype=int64),)

  3%|▎         | 29/993 [07:36<3:51:03, 14.38s/it]

(array([], dtype=int64),)

  3%|▎         | 30/993 [07:53<4:00:07, 14.96s/it]

(array([], dtype=int64),)

  3%|▎         | 31/993 [08:12<4:19:03, 16.16s/it]

(array([], dtype=int64),)

  3%|▎         | 32/993 [08:29<4:23:59, 16.48s/it]

(array([], dtype=int64),)

  3%|▎         | 34/993 [08:44<3:40:35, 13.80s/it]

(array([], dtype=int64),)

  4%|▎         | 35/993 [09:05<4:14:30, 15.94s/it]

(array([], dtype=int64),)

  4%|▎         | 36/993 [09:26<4:37:51, 17.42s/it]

(array([], dtype=int64),)

  4%|▎         | 37/993 [09:46<4:53:36, 18.43s/it]

(array([], dtype=int64),)

  4%|▍         | 39/993 [10:04<4:07:48, 15.59s/it]

(array([], dtype=int64),)

  4%|▍         | 40/993 [10:27<4:40:27, 17.66s/it]

(array([], dtype=int64),)

  4%|▍         | 41/993 [10:48<4:58:08, 18.79s/it]

(array([], dtype=int64),)

  4%|▍         | 42/993 [11:08<5:04:10, 19.19s/it]

(array([], dtype=int64),)

  4%|▍         | 43/993 [11:25<4:53:10, 18.52s/it]

(array([], dtype=int64),)

  4%|▍         | 44/993 [11:43<4:48:16, 18.23s/it]

(array([], dtype=int64),)

  5%|▍         | 45/993 [12:05<5:04:39, 19.28s/it]

(array([], dtype=int64),)

  5%|▍         | 46/993 [12:24<5:06:30, 19.42s/it]

(array([], dtype=int64),)

  5%|▍         | 47/993 [12:41<4:51:44, 18.50s/it]

(array([], dtype=int64),)

  5%|▍         | 48/993 [12:59<4:47:55, 18.28s/it]

(array([], dtype=int64),)

  5%|▍         | 49/993 [13:15<4:37:29, 17.64s/it]

(array([], dtype=int64),)

  5%|▌         | 50/993 [13:27<4:14:20, 16.18s/it]

(array([], dtype=int64),)

  5%|▌         | 51/993 [13:45<4:22:33, 16.72s/it]

(array([], dtype=int64),)

  5%|▌         | 52/993 [14:01<4:16:47, 16.37s/it]

(array([], dtype=int64),)

  5%|▌         | 53/993 [14:16<4:11:38, 16.06s/it]

(array([], dtype=int64),)

  5%|▌         | 54/993 [14:30<4:01:22, 15.42s/it]

(array([], dtype=int64),)

  6%|▌         | 55/993 [14:51<4:26:57, 17.08s/it]

(array([], dtype=int64),)

  6%|▌         | 56/993 [15:20<5:23:17, 20.70s/it]

(array([], dtype=int64),)

  6%|▌         | 57/993 [15:41<5:24:21, 20.79s/it]

(array([], dtype=int64),)

  6%|▌         | 58/993 [15:58<5:05:06, 19.58s/it]

(array([], dtype=int64),)

  6%|▌         | 59/993 [16:17<5:00:03, 19.28s/it]

(array([], dtype=int64),)

  6%|▌         | 60/993 [16:35<4:55:43, 19.02s/it]

(array([], dtype=int64),)

  6%|▌         | 61/993 [16:56<5:05:41, 19.68s/it]

(array([], dtype=int64),)

  6%|▌         | 62/993 [17:14<4:56:07, 19.08s/it]

(array([], dtype=int64),)

  6%|▋         | 63/993 [17:31<4:48:16, 18.60s/it]

(array([], dtype=int64),)

  6%|▋         | 64/993 [17:52<4:57:16, 19.20s/it]

(array([], dtype=int64),)

  7%|▋         | 65/993 [18:11<4:55:41, 19.12s/it]

(array([], dtype=int64),)

  7%|▋         | 66/993 [18:29<4:49:58, 18.77s/it]

(array([], dtype=int64),)

  7%|▋         | 67/993 [18:49<4:55:48, 19.17s/it]

(array([], dtype=int64),)

  7%|▋         | 68/993 [19:07<4:50:15, 18.83s/it]

(array([], dtype=int64),)

  7%|▋         | 69/993 [19:25<4:45:55, 18.57s/it]

(array([], dtype=int64),)

  7%|▋         | 70/993 [19:43<4:44:22, 18.49s/it]

(array([], dtype=int64),)

  7%|▋         | 71/993 [20:06<5:02:03, 19.66s/it]

(array([], dtype=int64),)

  7%|▋         | 72/993 [20:24<4:54:40, 19.20s/it]

(array([], dtype=int64),)

  7%|▋         | 73/993 [20:40<4:39:42, 18.24s/it]

(array([], dtype=int64),)

  7%|▋         | 74/993 [20:56<4:30:14, 17.64s/it]

(array([], dtype=int64),)

  8%|▊         | 75/993 [21:13<4:24:55, 17.32s/it]

(array([], dtype=int64),)

  8%|▊         | 76/993 [21:31<4:29:37, 17.64s/it]

(array([], dtype=int64),)

  8%|▊         | 77/993 [21:47<4:22:03, 17.17s/it]

(array([], dtype=int64),)

  8%|▊         | 78/993 [22:07<4:35:53, 18.09s/it]

(array([], dtype=int64),)

  8%|▊         | 79/993 [22:28<4:45:37, 18.75s/it]

(array([], dtype=int64),)

  8%|▊         | 80/993 [22:49<4:58:18, 19.60s/it]

(array([], dtype=int64),)

  8%|▊         | 81/993 [23:11<5:06:05, 20.14s/it]

(array([], dtype=int64),)

  8%|▊         | 82/993 [23:30<5:01:16, 19.84s/it]

(array([], dtype=int64),)

  8%|▊         | 83/993 [23:49<4:58:47, 19.70s/it]

(array([], dtype=int64),)

  8%|▊         | 84/993 [24:17<5:35:21, 22.14s/it]

(array([], dtype=int64),)

  9%|▊         | 85/993 [24:36<5:19:01, 21.08s/it]

(array([], dtype=int64),)

  9%|▊         | 86/993 [24:53<5:02:52, 20.04s/it]

(array([], dtype=int64),)

  9%|▉         | 89/993 [25:17<4:07:31, 16.43s/it]

(array([], dtype=int64),)

 10%|▉         | 96/993 [25:41<3:07:25, 12.54s/it]

(array([], dtype=int64),)

 10%|▉         | 98/993 [26:02<2:56:07, 11.81s/it]

(array([], dtype=int64),)

 10%|▉         | 99/993 [26:14<2:58:45, 12.00s/it]

(array([], dtype=int64),)

 10%|█         | 100/993 [26:26<2:59:12, 12.04s/it]

(array([], dtype=int64),)

 10%|█         | 102/993 [26:36<2:28:01,  9.97s/it]

(array([], dtype=int64),)

 11%|█         | 105/993 [26:48<2:00:46,  8.16s/it]

(array([], dtype=int64),)

 11%|█         | 106/993 [26:58<2:06:33,  8.56s/it]

(array([], dtype=int64),)

 11%|█         | 107/993 [27:09<2:19:11,  9.43s/it]

(array([], dtype=int64),)

 11%|█         | 108/993 [27:25<2:48:08, 11.40s/it]

(array([], dtype=int64),)

 11%|█         | 109/993 [27:41<3:06:29, 12.66s/it]

(array([], dtype=int64),)

 11%|█         | 110/993 [27:56<3:15:36, 13.29s/it]

(array([], dtype=int64),)

 11%|█         | 111/993 [28:10<3:22:16, 13.76s/it]

(array([], dtype=int64),)

 11%|█▏        | 112/993 [28:26<3:28:52, 14.23s/it]

(array([], dtype=int64),)

 11%|█▏        | 113/993 [28:56<4:38:55, 19.02s/it]

(array([], dtype=int64),)

 11%|█▏        | 114/993 [29:12<4:23:44, 18.00s/it]

(array([], dtype=int64),)

 12%|█▏        | 115/993 [29:30<4:23:56, 18.04s/it]

(array([], dtype=int64),)

 12%|█▏        | 116/993 [29:58<5:09:15, 21.16s/it]

(array([], dtype=int64),)

 12%|█▏        | 117/993 [30:16<4:53:50, 20.13s/it]

(array([], dtype=int64),)

 12%|█▏        | 118/993 [30:45<5:34:25, 22.93s/it]

(array([], dtype=int64),)

 12%|█▏        | 119/993 [31:06<5:23:07, 22.18s/it]

(array([], dtype=int64),)

 12%|█▏        | 120/993 [31:25<5:07:34, 21.14s/it]

(array([], dtype=int64),)

 12%|█▏        | 121/993 [31:42<4:53:20, 20.18s/it]

(array([], dtype=int64),)

 12%|█▏        | 122/993 [32:02<4:48:06, 19.85s/it]

(array([], dtype=int64),)

 12%|█▏        | 123/993 [32:24<4:57:54, 20.55s/it]

(array([], dtype=int64),)

 12%|█▏        | 124/993 [32:44<4:54:50, 20.36s/it]

(array([], dtype=int64),)

 13%|█▎        | 125/993 [33:01<4:43:07, 19.57s/it]

(array([], dtype=int64),)

 13%|█▎        | 127/993 [33:21<3:59:50, 16.62s/it]

(array([], dtype=int64),)

 13%|█▎        | 128/993 [33:38<4:01:06, 16.72s/it]

(array([], dtype=int64),)

 13%|█▎        | 129/993 [33:57<4:12:19, 17.52s/it]

(array([], dtype=int64),)

 13%|█▎        | 130/993 [34:19<4:28:50, 18.69s/it]

(array([], dtype=int64),)

 13%|█▎        | 131/993 [34:39<4:35:24, 19.17s/it]

(array([], dtype=int64),)

 13%|█▎        | 132/993 [34:59<4:41:12, 19.60s/it]

(array([], dtype=int64),)

 13%|█▎        | 133/993 [35:20<4:46:47, 20.01s/it]

(array([], dtype=int64),)

 13%|█▎        | 134/993 [35:44<5:00:55, 21.02s/it]

(array([], dtype=int64),)

 14%|█▎        | 135/993 [36:11<5:26:51, 22.86s/it]

(array([], dtype=int64),)

 14%|█▎        | 136/993 [36:35<5:32:21, 23.27s/it]

(array([], dtype=int64),)

 14%|█▍        | 137/993 [37:00<5:40:18, 23.85s/it]

(array([], dtype=int64),)

 14%|█▍        | 138/993 [37:26<5:45:12, 24.23s/it]

(array([], dtype=int64),)

 14%|█▍        | 139/993 [37:42<5:12:39, 21.97s/it]

(array([], dtype=int64),)

 14%|█▍        | 140/993 [38:10<5:35:06, 23.57s/it]

(array([], dtype=int64),)

 14%|█▍        | 141/993 [38:29<5:18:43, 22.44s/it]

(array([], dtype=int64),)

 14%|█▍        | 142/993 [39:00<5:54:24, 24.99s/it]

(array([], dtype=int64),)

 14%|█▍        | 143/993 [39:28<6:05:07, 25.77s/it]

(array([], dtype=int64),)

 15%|█▍        | 144/993 [40:12<7:20:31, 31.13s/it]

(array([], dtype=int64),)

 15%|█▍        | 145/993 [40:32<6:33:22, 27.83s/it]

(array([], dtype=int64),)

 15%|█▍        | 146/993 [40:49<5:48:54, 24.72s/it]

(array([], dtype=int64),)

 15%|█▍        | 147/993 [41:07<5:20:36, 22.74s/it]

(array([], dtype=int64),)

 15%|█▍        | 148/993 [41:25<4:59:45, 21.28s/it]

(array([], dtype=int64),)

 15%|█▌        | 149/993 [41:46<4:58:39, 21.23s/it]

(array([], dtype=int64),)

 15%|█▌        | 150/993 [42:06<4:53:45, 20.91s/it]

(array([], dtype=int64),)

 15%|█▌        | 151/993 [42:27<4:53:28, 20.91s/it]

(array([], dtype=int64),)

 15%|█▌        | 152/993 [42:46<4:43:43, 20.24s/it]

(array([], dtype=int64),)

 15%|█▌        | 153/993 [43:02<4:25:49, 18.99s/it]

(array([], dtype=int64),)

 16%|█▌        | 154/993 [43:21<4:27:05, 19.10s/it]

(array([], dtype=int64),)

 16%|█▌        | 155/993 [43:41<4:30:45, 19.39s/it]

(array([], dtype=int64),)

 16%|█▌        | 156/993 [43:56<4:10:10, 17.93s/it]

(array([], dtype=int64),)

 16%|█▌        | 157/993 [44:14<4:08:49, 17.86s/it]

(array([], dtype=int64),)

 16%|█▌        | 158/993 [44:29<3:59:30, 17.21s/it]

(array([], dtype=int64),)

 16%|█▌        | 159/993 [44:46<3:56:39, 17.03s/it]

(array([], dtype=int64),)

 16%|█▌        | 160/993 [45:03<3:54:37, 16.90s/it]

(array([], dtype=int64),)

 16%|█▌        | 161/993 [45:30<4:36:40, 19.95s/it]

(array([], dtype=int64),)

 16%|█▋        | 162/993 [45:51<4:40:16, 20.24s/it]

(array([], dtype=int64),)

 16%|█▋        | 163/993 [46:21<5:23:44, 23.40s/it]

(array([], dtype=int64),)

 17%|█▋        | 164/993 [46:44<5:18:46, 23.07s/it]

(array([], dtype=int64),)

 17%|█▋        | 165/993 [47:06<5:16:06, 22.91s/it]

(array([], dtype=int64),)

 17%|█▋        | 166/993 [47:29<5:16:33, 22.97s/it]

(array([], dtype=int64),)

 17%|█▋        | 167/993 [47:53<5:20:07, 23.25s/it]

(array([], dtype=int64),)

 17%|█▋        | 169/993 [48:13<4:24:54, 19.29s/it]

(array([], dtype=int64),)

 17%|█▋        | 170/993 [48:29<4:08:22, 18.11s/it]

(array([], dtype=int64),)

 17%|█▋        | 171/993 [48:51<4:26:29, 19.45s/it]

(array([], dtype=int64),)

 17%|█▋        | 172/993 [49:10<4:25:25, 19.40s/it]

(array([], dtype=int64),)

 17%|█▋        | 173/993 [49:28<4:17:37, 18.85s/it]

(array([], dtype=int64),)

 18%|█▊        | 174/993 [49:59<5:06:49, 22.48s/it]

(array([], dtype=int64),)

 18%|█▊        | 175/993 [50:20<4:59:04, 21.94s/it]

(array([], dtype=int64),)

 18%|█▊        | 176/993 [50:53<5:45:49, 25.40s/it]

(array([], dtype=int64),)

 18%|█▊        | 177/993 [51:15<5:29:27, 24.23s/it]

(array([], dtype=int64),)

 18%|█▊        | 178/993 [51:50<6:12:52, 27.45s/it]

(array([], dtype=int64),)

 18%|█▊        | 179/993 [52:20<6:26:02, 28.45s/it]

(array([], dtype=int64),)

 18%|█▊        | 180/993 [52:38<5:39:56, 25.09s/it]

(array([], dtype=int64),)

 18%|█▊        | 181/993 [53:06<5:52:18, 26.03s/it]

(array([], dtype=int64),)

 18%|█▊        | 182/993 [53:26<5:29:37, 24.39s/it]

(array([], dtype=int64),)

 18%|█▊        | 183/993 [53:44<5:02:07, 22.38s/it]

(array([], dtype=int64),)

 19%|█▊        | 184/993 [54:04<4:50:46, 21.57s/it]

(array([], dtype=int64),)

 19%|█▊        | 185/993 [54:22<4:35:14, 20.44s/it]

(array([], dtype=int64),)

 19%|█▊        | 186/993 [54:39<4:21:33, 19.45s/it]

(array([], dtype=int64),)

 19%|█▉        | 187/993 [54:58<4:21:37, 19.48s/it]

(array([], dtype=int64),)

 19%|█▉        | 188/993 [55:19<4:26:12, 19.84s/it]

(array([], dtype=int64),)

 19%|█▉        | 189/993 [55:36<4:15:07, 19.04s/it]

(array([], dtype=int64),)

 19%|█▉        | 190/993 [55:52<4:03:07, 18.17s/it]

(array([], dtype=int64),)

 19%|█▉        | 191/993 [56:13<4:15:01, 19.08s/it]

(array([], dtype=int64),)

 19%|█▉        | 192/993 [56:36<4:26:40, 19.98s/it]

(array([], dtype=int64),)

 19%|█▉        | 193/993 [56:55<4:22:26, 19.68s/it]

(array([], dtype=int64),)

 20%|█▉        | 195/993 [57:16<3:45:09, 16.93s/it]

(array([], dtype=int64),)

 20%|█▉        | 196/993 [57:39<4:11:21, 18.92s/it]

(array([], dtype=int64),)

 20%|█▉        | 197/993 [58:05<4:40:24, 21.14s/it]

(array([], dtype=int64),)

 20%|█▉        | 198/993 [58:32<5:00:02, 22.65s/it]

(array([], dtype=int64),)

 20%|██        | 199/993 [58:55<5:04:05, 22.98s/it]

(array([], dtype=int64),)

 20%|██        | 200/993 [59:20<5:11:43, 23.59s/it]

(array([], dtype=int64),)

 20%|██        | 201/993 [59:55<5:55:33, 26.94s/it]

(array([], dtype=int64),)

 20%|██        | 202/993 [1:00:12<5:14:55, 23.89s/it]

(array([], dtype=int64),)

 20%|██        | 203/993 [1:00:39<5:26:59, 24.83s/it]

(array([], dtype=int64),)

 21%|██        | 204/993 [1:00:56<4:57:45, 22.64s/it]

(array([], dtype=int64),)

 21%|██        | 205/993 [1:01:16<4:43:16, 21.57s/it]

(array([], dtype=int64),)

 21%|██        | 206/993 [1:01:33<4:26:12, 20.29s/it]

(array([], dtype=int64),)

 21%|██        | 207/993 [1:01:51<4:18:34, 19.74s/it]

(array([], dtype=int64),)

 21%|██        | 208/993 [1:02:21<4:57:08, 22.71s/it]

(array([], dtype=int64),)

 21%|██        | 209/993 [1:02:47<5:11:06, 23.81s/it]

(array([], dtype=int64),)

 21%|██        | 210/993 [1:03:03<4:39:39, 21.43s/it]

(array([], dtype=int64),)

 21%|██        | 211/993 [1:03:18<4:13:04, 19.42s/it]

(array([], dtype=int64),)

 21%|██▏       | 212/993 [1:03:35<4:04:49, 18.81s/it]

(array([], dtype=int64),)

 21%|██▏       | 213/993 [1:03:53<3:58:22, 18.34s/it]

(array([], dtype=int64),)

 22%|██▏       | 214/993 [1:04:10<3:56:33, 18.22s/it]

(array([], dtype=int64),)

 22%|██▏       | 215/993 [1:04:29<3:56:51, 18.27s/it]

(array([], dtype=int64),)

 22%|██▏       | 216/993 [1:04:50<4:09:17, 19.25s/it]

(array([], dtype=int64),)

 22%|██▏       | 217/993 [1:05:07<3:57:06, 18.33s/it]

(array([], dtype=int64),)

 22%|██▏       | 218/993 [1:05:41<4:57:46, 23.05s/it]

(array([], dtype=int64),)

 22%|██▏       | 219/993 [1:05:55<4:24:51, 20.53s/it]

(array([], dtype=int64),)

 22%|██▏       | 220/993 [1:06:10<4:01:54, 18.78s/it]

(array([], dtype=int64),)

 22%|██▏       | 221/993 [1:06:27<3:56:10, 18.36s/it]

(array([], dtype=int64),)

 22%|██▏       | 222/993 [1:07:00<4:50:11, 22.58s/it]

(array([], dtype=int64),)

 22%|██▏       | 223/993 [1:07:17<4:30:45, 21.10s/it]

(array([], dtype=int64),)

 23%|██▎       | 224/993 [1:07:38<4:27:25, 20.87s/it]

(array([], dtype=int64),)

 23%|██▎       | 225/993 [1:08:02<4:39:41, 21.85s/it]

(array([], dtype=int64),)

 23%|██▎       | 226/993 [1:08:23<4:36:12, 21.61s/it]

(array([], dtype=int64),)

 23%|██▎       | 227/993 [1:09:02<5:43:52, 26.94s/it]

(array([], dtype=int64),)

 23%|██▎       | 228/993 [1:09:30<5:44:58, 27.06s/it]

(array([], dtype=int64),)

 23%|██▎       | 229/993 [1:10:00<5:56:54, 28.03s/it]

(array([], dtype=int64),)

 23%|██▎       | 230/993 [1:10:37<6:30:10, 30.68s/it]

(array([], dtype=int64),)

 23%|██▎       | 231/993 [1:10:52<5:29:13, 25.92s/it]

(array([], dtype=int64),)

 23%|██▎       | 232/993 [1:11:21<5:42:01, 26.97s/it]

(array([], dtype=int64),)

 23%|██▎       | 233/993 [1:11:44<5:25:43, 25.72s/it]

(array([], dtype=int64),)

 24%|██▎       | 234/993 [1:12:03<5:01:16, 23.82s/it]

(array([], dtype=int64),)

 24%|██▎       | 235/993 [1:12:23<4:47:08, 22.73s/it]

(array([], dtype=int64),)

 24%|██▍       | 237/993 [1:12:45<4:00:22, 19.08s/it]

(array([], dtype=int64),)

 24%|██▍       | 238/993 [1:13:18<4:55:07, 23.45s/it]

(array([], dtype=int64),)

 24%|██▍       | 239/993 [1:13:29<4:08:54, 19.81s/it]

(array([], dtype=int64),)

 24%|██▍       | 241/993 [1:14:01<3:53:14, 18.61s/it]

(array([], dtype=int64),)

 24%|██▍       | 242/993 [1:14:34<4:44:40, 22.74s/it]

(array([], dtype=int64),)

 24%|██▍       | 243/993 [1:14:53<4:32:59, 21.84s/it]

(array([], dtype=int64),)

 25%|██▍       | 244/993 [1:15:13<4:23:50, 21.14s/it]

(array([], dtype=int64),)

 25%|██▍       | 245/993 [1:15:31<4:12:58, 20.29s/it]

(array([], dtype=int64),)

 25%|██▍       | 246/993 [1:15:48<4:01:40, 19.41s/it]

(array([], dtype=int64),)

 25%|██▍       | 247/993 [1:16:10<4:07:48, 19.93s/it]

(array([], dtype=int64),)

 25%|██▍       | 248/993 [1:16:30<4:09:17, 20.08s/it]

(array([], dtype=int64),)

 25%|██▌       | 249/993 [1:16:48<4:01:47, 19.50s/it]

(array([], dtype=int64),)

 25%|██▌       | 250/993 [1:17:08<4:03:22, 19.65s/it]

(array([], dtype=int64),)

 25%|██▌       | 251/993 [1:17:31<4:14:55, 20.61s/it]

(array([], dtype=int64),)

 25%|██▌       | 252/993 [1:17:54<4:23:21, 21.33s/it]

(array([], dtype=int64),)

 25%|██▌       | 253/993 [1:18:17<4:29:02, 21.81s/it]

(array([], dtype=int64),)

 26%|██▌       | 254/993 [1:18:38<4:26:03, 21.60s/it]

(array([], dtype=int64),)

 26%|██▌       | 255/993 [1:18:59<4:23:21, 21.41s/it]

(array([], dtype=int64),)

 26%|██▌       | 256/993 [1:19:19<4:19:13, 21.10s/it]

(array([], dtype=int64),)

 26%|██▌       | 257/993 [1:19:41<4:22:21, 21.39s/it]

(array([], dtype=int64),)

 26%|██▌       | 258/993 [1:20:04<4:28:04, 21.88s/it]

(array([], dtype=int64),)

 26%|██▌       | 259/993 [1:20:27<4:31:33, 22.20s/it]

(array([], dtype=int64),)

 26%|██▌       | 260/993 [1:20:50<4:33:57, 22.43s/it]

(array([], dtype=int64),)

 26%|██▋       | 261/993 [1:21:20<4:58:48, 24.49s/it]

(array([], dtype=int64),)

 26%|██▋       | 262/993 [1:21:49<5:17:13, 26.04s/it]

(array([], dtype=int64),)

 26%|██▋       | 263/993 [1:22:14<5:13:22, 25.76s/it]

(array([], dtype=int64),)

 27%|██▋       | 264/993 [1:22:41<5:17:07, 26.10s/it]

(array([], dtype=int64),)

 27%|██▋       | 265/993 [1:23:05<5:07:23, 25.33s/it]

(array([], dtype=int64),)

 27%|██▋       | 266/993 [1:23:25<4:46:44, 23.67s/it]

(array([], dtype=int64),)

 27%|██▋       | 267/993 [1:23:46<4:39:23, 23.09s/it]

(array([], dtype=int64),)

 27%|██▋       | 268/993 [1:24:08<4:34:36, 22.73s/it]

(array([], dtype=int64),)

 27%|██▋       | 269/993 [1:24:24<4:08:49, 20.62s/it]

(array([], dtype=int64),)

 27%|██▋       | 270/993 [1:24:44<4:06:04, 20.42s/it]

(array([], dtype=int64),)

 27%|██▋       | 271/993 [1:25:07<4:14:14, 21.13s/it]

(array([], dtype=int64),)

 27%|██▋       | 272/993 [1:25:27<4:09:33, 20.77s/it]

(array([], dtype=int64),)

 27%|██▋       | 273/993 [1:25:46<4:02:22, 20.20s/it]

(array([], dtype=int64),)

 28%|██▊       | 274/993 [1:26:02<3:47:57, 19.02s/it]

(array([], dtype=int64),)

 28%|██▊       | 275/993 [1:26:23<3:54:26, 19.59s/it]

(array([], dtype=int64),)

 28%|██▊       | 276/993 [1:26:44<4:00:33, 20.13s/it]

(array([], dtype=int64),)

 28%|██▊       | 277/993 [1:27:04<3:59:04, 20.03s/it]

(array([], dtype=int64),)

 28%|██▊       | 278/993 [1:27:20<3:46:20, 18.99s/it]

(array([], dtype=int64),)

 28%|██▊       | 279/993 [1:27:42<3:53:51, 19.65s/it]

(array([], dtype=int64),)

 28%|██▊       | 280/993 [1:28:03<3:58:55, 20.11s/it]

(array([], dtype=int64),)

 28%|██▊       | 281/993 [1:28:25<4:04:19, 20.59s/it]

(array([], dtype=int64),)

 28%|██▊       | 282/993 [1:28:40<3:44:42, 18.96s/it]

(array([], dtype=int64),)

 28%|██▊       | 283/993 [1:29:01<3:50:58, 19.52s/it]

(array([], dtype=int64),)

 29%|██▊       | 284/993 [1:29:24<4:04:06, 20.66s/it]

(array([], dtype=int64),)

 29%|██▊       | 285/993 [1:29:44<4:03:03, 20.60s/it]

(array([], dtype=int64),)

 29%|██▉       | 286/993 [1:30:09<4:17:17, 21.84s/it]

(array([], dtype=int64),)

 29%|██▉       | 287/993 [1:30:26<3:59:25, 20.35s/it]

(array([], dtype=int64),)

 29%|██▉       | 288/993 [1:30:43<3:46:52, 19.31s/it]

(array([], dtype=int64),)

 29%|██▉       | 289/993 [1:30:59<3:35:52, 18.40s/it]

(array([], dtype=int64),)

 29%|██▉       | 290/993 [1:31:15<3:26:51, 17.66s/it]

(array([], dtype=int64),)

 29%|██▉       | 291/993 [1:31:33<3:28:16, 17.80s/it]

(array([], dtype=int64),)

 29%|██▉       | 292/993 [1:31:52<3:32:26, 18.18s/it]

(array([], dtype=int64),)

 30%|██▉       | 293/993 [1:32:13<3:42:08, 19.04s/it]

(array([], dtype=int64),)

 30%|██▉       | 294/993 [1:32:36<3:54:00, 20.09s/it]

(array([], dtype=int64),)

 30%|██▉       | 295/993 [1:32:57<3:56:10, 20.30s/it]

(array([], dtype=int64),)

 30%|██▉       | 296/993 [1:33:16<3:51:40, 19.94s/it]

(array([], dtype=int64),)

 30%|██▉       | 297/993 [1:33:44<4:21:28, 22.54s/it]

(array([], dtype=int64),)

 30%|███       | 298/993 [1:34:08<4:25:38, 22.93s/it]

(array([], dtype=int64),)

 30%|███       | 299/993 [1:34:25<4:02:48, 20.99s/it]

(array([], dtype=int64),)

 30%|███       | 300/993 [1:34:42<3:51:17, 20.02s/it]

(array([], dtype=int64),)

 30%|███       | 301/993 [1:34:59<3:39:44, 19.05s/it]

(array([], dtype=int64),)

 30%|███       | 302/993 [1:35:16<3:31:28, 18.36s/it]

(array([], dtype=int64),)

 31%|███       | 303/993 [1:35:37<3:39:13, 19.06s/it]

(array([], dtype=int64),)

 31%|███       | 304/993 [1:35:52<3:26:23, 17.97s/it]

(array([], dtype=int64),)

 31%|███       | 305/993 [1:36:02<2:57:39, 15.49s/it]

(array([], dtype=int64),)

 31%|███       | 306/993 [1:36:21<3:09:29, 16.55s/it]

(array([], dtype=int64),)

 31%|███       | 307/993 [1:36:35<3:01:23, 15.87s/it]

(array([], dtype=int64),)

 31%|███       | 308/993 [1:36:53<3:07:47, 16.45s/it]

(array([], dtype=int64),)

 31%|███       | 309/993 [1:37:09<3:07:23, 16.44s/it]

(array([], dtype=int64),)

 31%|███       | 310/993 [1:37:24<3:00:16, 15.84s/it]

(array([], dtype=int64),)

 31%|███▏      | 311/993 [1:37:40<3:01:42, 15.99s/it]

(array([], dtype=int64),)

 31%|███▏      | 312/993 [1:38:00<3:15:07, 17.19s/it]

(array([], dtype=int64),)

 32%|███▏      | 313/993 [1:38:16<3:12:17, 16.97s/it]

(array([], dtype=int64),)

 32%|███▏      | 314/993 [1:38:35<3:17:38, 17.46s/it]

(array([], dtype=int64),)

 32%|███▏      | 315/993 [1:38:56<3:28:36, 18.46s/it]

(array([], dtype=int64),)

 32%|███▏      | 316/993 [1:39:13<3:23:36, 18.04s/it]

(array([], dtype=int64),)

 32%|███▏      | 317/993 [1:39:29<3:16:49, 17.47s/it]

(array([], dtype=int64),)

 32%|███▏      | 318/993 [1:39:48<3:20:56, 17.86s/it]

(array([], dtype=int64),)

 32%|███▏      | 319/993 [1:40:06<3:22:18, 18.01s/it]

(array([], dtype=int64),)

 32%|███▏      | 320/993 [1:40:22<3:15:17, 17.41s/it]

(array([], dtype=int64),)

 32%|███▏      | 321/993 [1:40:41<3:21:19, 17.98s/it]

(array([], dtype=int64),)

 32%|███▏      | 322/993 [1:40:58<3:16:36, 17.58s/it]

(array([], dtype=int64),)

 33%|███▎      | 323/993 [1:41:13<3:08:13, 16.86s/it]

(array([], dtype=int64),)

 33%|███▎      | 324/993 [1:41:33<3:16:32, 17.63s/it]

(array([], dtype=int64),)

 33%|███▎      | 325/993 [1:41:49<3:11:25, 17.19s/it]

(array([], dtype=int64),)

 33%|███▎      | 326/993 [1:42:06<3:11:25, 17.22s/it]

(array([], dtype=int64),)

 33%|███▎      | 327/993 [1:42:24<3:13:09, 17.40s/it]

(array([], dtype=int64),)

 33%|███▎      | 328/993 [1:42:41<3:11:50, 17.31s/it]

(array([], dtype=int64),)

 33%|███▎      | 329/993 [1:42:56<3:04:18, 16.65s/it]

(array([], dtype=int64),)

 33%|███▎      | 330/993 [1:43:16<3:13:45, 17.54s/it]

(array([], dtype=int64),)

 33%|███▎      | 331/993 [1:43:37<3:26:27, 18.71s/it]

(array([], dtype=int64),)

 33%|███▎      | 332/993 [1:44:01<3:41:44, 20.13s/it]

(array([], dtype=int64),)

 34%|███▎      | 333/993 [1:44:26<3:58:41, 21.70s/it]

(array([], dtype=int64),)

 34%|███▎      | 334/993 [1:44:51<4:09:12, 22.69s/it]

(array([], dtype=int64),)

 34%|███▎      | 335/993 [1:45:16<4:17:16, 23.46s/it]

(array([], dtype=int64),)

 34%|███▍      | 336/993 [1:45:37<4:06:14, 22.49s/it]

(array([], dtype=int64),)

 34%|███▍      | 337/993 [1:45:50<3:36:00, 19.76s/it]

(array([], dtype=int64),)

 34%|███▍      | 339/993 [1:46:05<2:56:00, 16.15s/it]

(array([], dtype=int64),)

 34%|███▍      | 340/993 [1:46:22<2:58:13, 16.38s/it]

(array([], dtype=int64),)

 34%|███▍      | 341/993 [1:46:38<2:54:38, 16.07s/it]

(array([], dtype=int64),)

 34%|███▍      | 342/993 [1:46:56<3:02:58, 16.86s/it]

(array([], dtype=int64),)

 35%|███▍      | 343/993 [1:47:12<2:59:53, 16.61s/it]

(array([], dtype=int64),)

 35%|███▍      | 344/993 [1:47:33<3:11:10, 17.67s/it]

(array([], dtype=int64),)

 35%|███▍      | 345/993 [1:47:49<3:05:46, 17.20s/it]

(array([], dtype=int64),)

 35%|███▍      | 346/993 [1:48:07<3:08:27, 17.48s/it]

(array([], dtype=int64),)

 35%|███▍      | 347/993 [1:48:27<3:15:53, 18.19s/it]

(array([], dtype=int64),)

 35%|███▌      | 348/993 [1:48:43<3:09:04, 17.59s/it]

(array([], dtype=int64),)

 35%|███▌      | 349/993 [1:49:00<3:07:11, 17.44s/it]

(array([], dtype=int64),)

 35%|███▌      | 350/993 [1:49:17<3:07:17, 17.48s/it]

(array([], dtype=int64),)

 35%|███▌      | 351/993 [1:49:36<3:11:53, 17.93s/it]

(array([], dtype=int64),)

 35%|███▌      | 352/993 [1:49:54<3:11:01, 17.88s/it]

(array([], dtype=int64),)

 36%|███▌      | 353/993 [1:50:11<3:06:50, 17.52s/it]

(array([], dtype=int64),)

 36%|███▌      | 354/993 [1:50:30<3:12:35, 18.08s/it]

(array([], dtype=int64),)

 36%|███▌      | 355/993 [1:50:45<3:02:30, 17.16s/it]

(array([], dtype=int64),)

 36%|███▌      | 356/993 [1:51:01<2:56:38, 16.64s/it]

(array([], dtype=int64),)

 36%|███▌      | 357/993 [1:51:16<2:52:53, 16.31s/it]

(array([], dtype=int64),)

 36%|███▌      | 358/993 [1:51:32<2:51:06, 16.17s/it]

(array([], dtype=int64),)

 36%|███▌      | 359/993 [1:51:53<3:04:43, 17.48s/it]

(array([], dtype=int64),)

 36%|███▋      | 360/993 [1:52:10<3:03:02, 17.35s/it]

(array([], dtype=int64),)

 36%|███▋      | 361/993 [1:52:25<2:56:19, 16.74s/it]

(array([], dtype=int64),)

 36%|███▋      | 362/993 [1:52:42<2:55:17, 16.67s/it]

(array([], dtype=int64),)

 37%|███▋      | 363/993 [1:52:59<2:56:06, 16.77s/it]

(array([], dtype=int64),)

 37%|███▋      | 364/993 [1:53:17<3:00:01, 17.17s/it]

(array([], dtype=int64),)

 37%|███▋      | 365/993 [1:53:33<2:56:54, 16.90s/it]

(array([], dtype=int64),)

 37%|███▋      | 366/993 [1:53:50<2:57:35, 16.99s/it]

(array([], dtype=int64),)

 37%|███▋      | 367/993 [1:54:08<2:59:17, 17.18s/it]

(array([], dtype=int64),)

 37%|███▋      | 368/993 [1:54:25<2:59:03, 17.19s/it]

(array([], dtype=int64),)

 37%|███▋      | 369/993 [1:54:43<3:00:38, 17.37s/it]

(array([], dtype=int64),)

 37%|███▋      | 371/993 [1:55:02<2:35:23, 14.99s/it]

(array([], dtype=int64),)

 37%|███▋      | 372/993 [1:55:22<2:51:47, 16.60s/it]

(array([], dtype=int64),)

 38%|███▊      | 373/993 [1:55:44<3:08:15, 18.22s/it]

(array([], dtype=int64),)

 38%|███▊      | 374/993 [1:56:07<3:24:13, 19.80s/it]

(array([], dtype=int64),)

 38%|███▊      | 375/993 [1:56:29<3:30:10, 20.41s/it]

(array([], dtype=int64),)

 38%|███▊      | 376/993 [1:56:48<3:24:31, 19.89s/it]

(array([], dtype=int64),)

 38%|███▊      | 377/993 [1:57:02<3:07:36, 18.27s/it]

(array([], dtype=int64),)

 38%|███▊      | 378/993 [1:57:17<2:56:24, 17.21s/it]

(array([], dtype=int64),)

 38%|███▊      | 379/993 [1:57:35<2:56:35, 17.26s/it]

(array([], dtype=int64),)

 38%|███▊      | 380/993 [1:57:50<2:51:19, 16.77s/it]

(array([], dtype=int64),)

 38%|███▊      | 381/993 [1:58:08<2:52:54, 16.95s/it]

(array([], dtype=int64),)

 38%|███▊      | 382/993 [1:58:26<2:55:54, 17.27s/it]

(array([], dtype=int64),)

 39%|███▊      | 383/993 [1:58:40<2:45:34, 16.29s/it]

(array([], dtype=int64),)

 39%|███▊      | 384/993 [1:58:55<2:44:03, 16.16s/it]

(array([], dtype=int64),)

 39%|███▉      | 385/993 [1:59:14<2:50:41, 16.85s/it]

(array([], dtype=int64),)

 39%|███▉      | 386/993 [1:59:31<2:52:33, 17.06s/it]

(array([], dtype=int64),)

 39%|███▉      | 387/993 [1:59:47<2:47:18, 16.57s/it]

(array([], dtype=int64),)

 39%|███▉      | 388/993 [2:00:05<2:50:37, 16.92s/it]

(array([], dtype=int64),)

 39%|███▉      | 389/993 [2:00:20<2:46:24, 16.53s/it]

(array([], dtype=int64),)

 39%|███▉      | 390/993 [2:00:37<2:47:33, 16.67s/it]

(array([], dtype=int64),)

 39%|███▉      | 391/993 [2:00:55<2:49:48, 16.92s/it]

(array([], dtype=int64),)

 39%|███▉      | 392/993 [2:01:12<2:49:58, 16.97s/it]

(array([], dtype=int64),)

 40%|███▉      | 393/993 [2:01:29<2:48:54, 16.89s/it]

(array([], dtype=int64),)

 40%|███▉      | 394/993 [2:01:47<2:53:48, 17.41s/it]

(array([], dtype=int64),)

 40%|███▉      | 395/993 [2:02:03<2:48:46, 16.93s/it]

(array([], dtype=int64),)

 40%|███▉      | 396/993 [2:02:20<2:47:48, 16.86s/it]

(array([], dtype=int64),)

 40%|███▉      | 397/993 [2:02:36<2:47:06, 16.82s/it]

(array([], dtype=int64),)

 40%|████      | 398/993 [2:03:03<3:17:02, 19.87s/it]

(array([], dtype=int64),)

 40%|████      | 399/993 [2:03:21<3:09:27, 19.14s/it]

(array([], dtype=int64),)

 40%|████      | 400/993 [2:03:42<3:14:11, 19.65s/it]

(array([], dtype=int64),)

 40%|████      | 401/993 [2:04:13<3:49:04, 23.22s/it]

(array([], dtype=int64),)

 40%|████      | 402/993 [2:04:31<3:32:21, 21.56s/it]

(array([], dtype=int64),)

 41%|████      | 403/993 [2:04:50<3:25:59, 20.95s/it]

(array([], dtype=int64),)

 41%|████      | 404/993 [2:05:03<3:02:12, 18.56s/it]

(array([], dtype=int64),)

 41%|████      | 405/993 [2:05:23<3:04:38, 18.84s/it]

(array([], dtype=int64),)

 41%|████      | 406/993 [2:05:44<3:12:14, 19.65s/it]

(array([], dtype=int64),)

 41%|████      | 407/993 [2:06:07<3:20:32, 20.53s/it]

(array([], dtype=int64),)

 41%|████      | 408/993 [2:06:25<3:11:44, 19.67s/it]

(array([], dtype=int64),)

 41%|████      | 409/993 [2:06:51<3:31:58, 21.78s/it]

(array([], dtype=int64),)

 41%|████▏     | 410/993 [2:07:15<3:37:05, 22.34s/it]

(array([], dtype=int64),)

 41%|████▏     | 411/993 [2:07:39<3:42:14, 22.91s/it]

(array([], dtype=int64),)

 41%|████▏     | 412/993 [2:08:05<3:50:00, 23.75s/it]

(array([], dtype=int64),)

 42%|████▏     | 413/993 [2:08:27<3:45:30, 23.33s/it]

(array([], dtype=int64),)

 42%|████▏     | 414/993 [2:08:46<3:30:47, 21.84s/it]

(array([], dtype=int64),)

 42%|████▏     | 415/993 [2:09:05<3:24:21, 21.21s/it]

(array([], dtype=int64),)

 42%|████▏     | 416/993 [2:09:29<3:32:01, 22.05s/it]

(array([], dtype=int64),)

 42%|████▏     | 417/993 [2:09:49<3:24:45, 21.33s/it]

(array([], dtype=int64),)

 42%|████▏     | 418/993 [2:10:06<3:11:26, 19.98s/it]

(array([], dtype=int64),)

 42%|████▏     | 419/993 [2:10:21<2:57:10, 18.52s/it]

(array([], dtype=int64),)

 42%|████▏     | 420/993 [2:10:41<2:59:39, 18.81s/it]

(array([], dtype=int64),)

 42%|████▏     | 421/993 [2:10:57<2:53:54, 18.24s/it]

(array([], dtype=int64),)

 42%|████▏     | 422/993 [2:11:14<2:47:44, 17.63s/it]

(array([], dtype=int64),)

 43%|████▎     | 423/993 [2:11:34<2:56:01, 18.53s/it]

(array([], dtype=int64),)

 43%|████▎     | 424/993 [2:11:56<3:05:40, 19.58s/it]

(array([], dtype=int64),)

 43%|████▎     | 425/993 [2:12:14<3:01:04, 19.13s/it]

(array([], dtype=int64),)

 43%|████▎     | 426/993 [2:12:33<3:00:00, 19.05s/it]

(array([], dtype=int64),)

 43%|████▎     | 427/993 [2:12:51<2:57:03, 18.77s/it]

(array([], dtype=int64),)

 43%|████▎     | 428/993 [2:13:20<3:25:07, 21.78s/it]

(array([], dtype=int64),)

 43%|████▎     | 429/993 [2:13:46<3:37:00, 23.09s/it]

(array([], dtype=int64),)

 43%|████▎     | 430/993 [2:14:04<3:21:51, 21.51s/it]

(array([], dtype=int64),)

 43%|████▎     | 431/993 [2:14:24<3:17:46, 21.11s/it]

(array([], dtype=int64),)

 44%|████▎     | 432/993 [2:14:41<3:04:37, 19.75s/it]

(array([], dtype=int64),)

 44%|████▎     | 433/993 [2:14:58<2:57:18, 19.00s/it]

(array([], dtype=int64),)

 44%|████▎     | 434/993 [2:15:18<2:59:01, 19.22s/it]

(array([], dtype=int64),)

 44%|████▍     | 435/993 [2:15:33<2:46:37, 17.92s/it]

(array([], dtype=int64),)

 44%|████▍     | 436/993 [2:15:51<2:47:17, 18.02s/it]

(array([], dtype=int64),)

 44%|████▍     | 437/993 [2:16:10<2:48:49, 18.22s/it]

(array([], dtype=int64),)

 44%|████▍     | 438/993 [2:16:26<2:42:28, 17.57s/it]

(array([], dtype=int64),)

 44%|████▍     | 439/993 [2:16:42<2:38:26, 17.16s/it]

(array([], dtype=int64),)

 44%|████▍     | 440/993 [2:17:01<2:43:49, 17.78s/it]

(array([], dtype=int64),)

 44%|████▍     | 441/993 [2:17:19<2:43:41, 17.79s/it]

(array([], dtype=int64),)

 45%|████▍     | 442/993 [2:17:40<2:51:48, 18.71s/it]

(array([], dtype=int64),)

 45%|████▍     | 443/993 [2:18:05<3:08:20, 20.55s/it]

(array([], dtype=int64),)

 45%|████▍     | 444/993 [2:18:29<3:19:04, 21.76s/it]

(array([], dtype=int64),)

 45%|████▍     | 445/993 [2:18:50<3:15:52, 21.45s/it]

(array([], dtype=int64),)

 45%|████▍     | 446/993 [2:19:15<3:26:25, 22.64s/it]

(array([], dtype=int64),)

 45%|████▌     | 447/993 [2:19:33<3:11:40, 21.06s/it]

(array([], dtype=int64),)

 45%|████▌     | 448/993 [2:19:51<3:04:46, 20.34s/it]

(array([], dtype=int64),)

 45%|████▌     | 449/993 [2:20:12<3:04:24, 20.34s/it]

(array([], dtype=int64),)

 45%|████▌     | 450/993 [2:20:35<3:12:01, 21.22s/it]

(array([], dtype=int64),)

 45%|████▌     | 451/993 [2:20:55<3:08:36, 20.88s/it]

(array([], dtype=int64),)

 46%|████▌     | 452/993 [2:21:14<3:01:52, 20.17s/it]

(array([], dtype=int64),)

 46%|████▌     | 453/993 [2:21:35<3:03:32, 20.39s/it]

(array([], dtype=int64),)

 46%|████▌     | 454/993 [2:21:58<3:10:09, 21.17s/it]

(array([], dtype=int64),)

 46%|████▌     | 455/993 [2:22:15<3:00:49, 20.17s/it]

(array([], dtype=int64),)

 46%|████▌     | 456/993 [2:22:37<3:05:04, 20.68s/it]

(array([], dtype=int64),)

 46%|████▌     | 457/993 [2:22:58<3:03:58, 20.59s/it]

(array([], dtype=int64),)

 46%|████▌     | 459/993 [2:23:20<2:37:48, 17.73s/it]

(array([], dtype=int64),)

 46%|████▋     | 460/993 [2:23:42<2:48:45, 19.00s/it]

(array([], dtype=int64),)

 46%|████▋     | 461/993 [2:24:04<2:56:41, 19.93s/it]

(array([], dtype=int64),)

 47%|████▋     | 462/993 [2:24:30<3:12:00, 21.70s/it]

(array([], dtype=int64),)

 47%|████▋     | 463/993 [2:24:49<3:04:41, 20.91s/it]

(array([], dtype=int64),)

 47%|████▋     | 464/993 [2:25:04<2:48:36, 19.12s/it]

(array([], dtype=int64),)

 47%|████▋     | 465/993 [2:25:27<3:00:29, 20.51s/it]

(array([], dtype=int64),)

 47%|████▋     | 466/993 [2:25:47<2:58:01, 20.27s/it]

(array([], dtype=int64),)

 47%|████▋     | 467/993 [2:26:03<2:46:53, 19.04s/it]

(array([], dtype=int64),)

 47%|████▋     | 468/993 [2:26:19<2:38:47, 18.15s/it]

(array([], dtype=int64),)

 47%|████▋     | 469/993 [2:26:36<2:34:50, 17.73s/it]

(array([], dtype=int64),)

 47%|████▋     | 470/993 [2:26:51<2:27:40, 16.94s/it]

(array([], dtype=int64),)

 47%|████▋     | 471/993 [2:27:10<2:31:30, 17.42s/it]

(array([], dtype=int64),)

 48%|████▊     | 472/993 [2:27:27<2:29:53, 17.26s/it]

(array([], dtype=int64),)

 48%|████▊     | 474/993 [2:27:44<2:07:26, 14.73s/it]

(array([], dtype=int64),)

 48%|████▊     | 475/993 [2:28:03<2:17:22, 15.91s/it]

(array([], dtype=int64),)

 48%|████▊     | 476/993 [2:28:22<2:24:56, 16.82s/it]

(array([], dtype=int64),)

 48%|████▊     | 477/993 [2:28:46<2:42:33, 18.90s/it]

(array([], dtype=int64),)

 48%|████▊     | 478/993 [2:29:21<3:23:54, 23.76s/it]

(array([], dtype=int64),)

 48%|████▊     | 479/993 [2:29:45<3:24:51, 23.91s/it]

(array([], dtype=int64),)

 48%|████▊     | 480/993 [2:30:06<3:17:33, 23.11s/it]

(array([], dtype=int64),)

 48%|████▊     | 481/993 [2:30:27<3:10:00, 22.27s/it]

(array([], dtype=int64),)

 49%|████▊     | 482/993 [2:30:43<2:55:45, 20.64s/it]

(array([], dtype=int64),)

 49%|████▊     | 483/993 [2:31:02<2:51:34, 20.19s/it]

(array([], dtype=int64),)

 49%|████▊     | 484/993 [2:31:21<2:47:34, 19.75s/it]

(array([], dtype=int64),)

 49%|████▉     | 485/993 [2:31:37<2:37:42, 18.63s/it]

(array([], dtype=int64),)

 49%|████▉     | 486/993 [2:31:56<2:38:09, 18.72s/it]

(array([], dtype=int64),)

 49%|████▉     | 487/993 [2:32:11<2:29:05, 17.68s/it]

(array([], dtype=int64),)

 49%|████▉     | 488/993 [2:32:30<2:32:06, 18.07s/it]

(array([], dtype=int64),)

 49%|████▉     | 489/993 [2:32:46<2:25:30, 17.32s/it]

(array([], dtype=int64),)

 49%|████▉     | 490/993 [2:33:04<2:26:00, 17.42s/it]

(array([], dtype=int64),)

 49%|████▉     | 491/993 [2:33:25<2:35:28, 18.58s/it]

(array([], dtype=int64),)

 50%|████▉     | 492/993 [2:33:42<2:31:51, 18.19s/it]

(array([], dtype=int64),)

 50%|████▉     | 493/993 [2:34:01<2:34:02, 18.48s/it]

(array([], dtype=int64),)

 50%|████▉     | 494/993 [2:34:17<2:26:04, 17.56s/it]

(array([], dtype=int64),)

 50%|████▉     | 495/993 [2:34:38<2:36:07, 18.81s/it]

(array([], dtype=int64),)

 50%|████▉     | 496/993 [2:35:15<3:19:09, 24.04s/it]

(array([], dtype=int64),)

 50%|█████     | 497/993 [2:35:30<2:57:58, 21.53s/it]

(array([], dtype=int64),)

 50%|█████     | 498/993 [2:35:46<2:42:10, 19.66s/it]

(array([], dtype=int64),)

 50%|█████     | 499/993 [2:36:03<2:36:37, 19.02s/it]

(array([], dtype=int64),)

 50%|█████     | 500/993 [2:36:21<2:32:14, 18.53s/it]

(array([], dtype=int64),)

 50%|█████     | 501/993 [2:36:40<2:33:32, 18.72s/it]

(array([], dtype=int64),)

 51%|█████     | 502/993 [2:36:58<2:31:15, 18.48s/it]

(array([], dtype=int64),)

 51%|█████     | 503/993 [2:37:15<2:29:00, 18.25s/it]

(array([], dtype=int64),)

 51%|█████     | 504/993 [2:37:38<2:40:31, 19.70s/it]

(array([], dtype=int64),)

 51%|█████     | 505/993 [2:38:00<2:43:38, 20.12s/it]

(array([], dtype=int64),)

 51%|█████     | 506/993 [2:38:22<2:49:24, 20.87s/it]

(array([], dtype=int64),)

 51%|█████     | 507/993 [2:38:41<2:43:42, 20.21s/it]

(array([], dtype=int64),)

 51%|█████     | 508/993 [2:39:03<2:47:02, 20.67s/it]

(array([], dtype=int64),)

 51%|█████▏    | 509/993 [2:39:19<2:37:17, 19.50s/it]

(array([], dtype=int64),)

 51%|█████▏    | 510/993 [2:39:40<2:38:43, 19.72s/it]

(array([], dtype=int64),)

 51%|█████▏    | 511/993 [2:40:07<2:56:21, 21.95s/it]

(array([], dtype=int64),)

 52%|█████▏    | 512/993 [2:40:37<3:15:02, 24.33s/it]

(array([], dtype=int64),)

 52%|█████▏    | 513/993 [2:41:00<3:12:01, 24.00s/it]

(array([], dtype=int64),)

 52%|█████▏    | 514/993 [2:41:28<3:20:54, 25.17s/it]

(array([], dtype=int64),)

 52%|█████▏    | 515/993 [2:41:54<3:21:58, 25.35s/it]

(array([], dtype=int64),)

 52%|█████▏    | 516/993 [2:42:12<3:05:30, 23.33s/it]

(array([], dtype=int64),)

 52%|█████▏    | 517/993 [2:42:33<2:58:02, 22.44s/it]

(array([], dtype=int64),)

 52%|█████▏    | 518/993 [2:42:52<2:51:24, 21.65s/it]

(array([], dtype=int64),)

 52%|█████▏    | 519/993 [2:43:09<2:39:08, 20.15s/it]

(array([], dtype=int64),)

 52%|█████▏    | 520/993 [2:43:32<2:45:47, 21.03s/it]

(array([], dtype=int64),)

 52%|█████▏    | 521/993 [2:43:53<2:46:04, 21.11s/it]

(array([], dtype=int64),)

 53%|█████▎    | 522/993 [2:44:11<2:37:05, 20.01s/it]

(array([], dtype=int64),)

 53%|█████▎    | 523/993 [2:44:30<2:34:08, 19.68s/it]

(array([], dtype=int64),)

 53%|█████▎    | 524/993 [2:44:50<2:35:57, 19.95s/it]

(array([], dtype=int64),)

 53%|█████▎    | 525/993 [2:45:16<2:47:56, 21.53s/it]

(array([], dtype=int64),)

 53%|█████▎    | 526/993 [2:45:42<2:58:03, 22.88s/it]

(array([], dtype=int64),)

 53%|█████▎    | 527/993 [2:45:59<2:45:54, 21.36s/it]

(array([], dtype=int64),)

 53%|█████▎    | 528/993 [2:46:18<2:38:35, 20.46s/it]

(array([], dtype=int64),)

 53%|█████▎    | 529/993 [2:46:32<2:22:54, 18.48s/it]

(array([], dtype=int64),)

 53%|█████▎    | 530/993 [2:46:49<2:20:08, 18.16s/it]

(array([], dtype=int64),)

 53%|█████▎    | 531/993 [2:47:21<2:52:08, 22.36s/it]

(array([], dtype=int64),)

 54%|█████▎    | 532/993 [2:47:41<2:46:32, 21.68s/it]

(array([], dtype=int64),)

 54%|█████▎    | 533/993 [2:48:04<2:48:19, 21.95s/it]

(array([], dtype=int64),)

 54%|█████▍    | 534/993 [2:48:25<2:46:52, 21.81s/it]

(array([], dtype=int64),)

 54%|█████▍    | 535/993 [2:48:48<2:48:13, 22.04s/it]

(array([], dtype=int64),)

 54%|█████▍    | 536/993 [2:49:11<2:51:03, 22.46s/it]

(array([], dtype=int64),)

 54%|█████▍    | 537/993 [2:49:31<2:45:05, 21.72s/it]

(array([], dtype=int64),)

 54%|█████▍    | 538/993 [2:49:53<2:45:39, 21.84s/it]

(array([], dtype=int64),)

 54%|█████▍    | 539/993 [2:50:20<2:55:30, 23.19s/it]

(array([], dtype=int64),)

 54%|█████▍    | 540/993 [2:50:44<2:57:00, 23.45s/it]

(array([], dtype=int64),)

 54%|█████▍    | 541/993 [2:51:09<3:01:22, 24.08s/it]

(array([], dtype=int64),)

 55%|█████▍    | 542/993 [2:51:33<2:58:57, 23.81s/it]

(array([], dtype=int64),)

 55%|█████▍    | 543/993 [2:51:57<3:00:27, 24.06s/it]

(array([], dtype=int64),)

 55%|█████▍    | 544/993 [2:52:25<3:09:24, 25.31s/it]

(array([], dtype=int64),)

 55%|█████▍    | 545/993 [2:52:52<3:11:33, 25.66s/it]

(array([], dtype=int64),)

 55%|█████▍    | 546/993 [2:53:11<2:57:24, 23.81s/it]

(array([], dtype=int64),)

 55%|█████▌    | 547/993 [2:53:26<2:35:21, 20.90s/it]

(array([], dtype=int64),)

 55%|█████▌    | 548/993 [2:53:46<2:34:17, 20.80s/it]

(array([], dtype=int64),)

 55%|█████▌    | 549/993 [2:54:06<2:31:37, 20.49s/it]

(array([], dtype=int64),)

 56%|█████▌    | 554/993 [2:54:18<1:50:09, 15.06s/it]

(array([], dtype=int64),)

 56%|█████▌    | 557/993 [2:54:55<1:43:19, 14.22s/it]

(array([], dtype=int64),)

 56%|█████▌    | 558/993 [2:55:28<2:25:37, 20.09s/it]

(array([], dtype=int64),)

 56%|█████▋    | 559/993 [2:55:44<2:15:58, 18.80s/it]

(array([], dtype=int64),)

 56%|█████▋    | 560/993 [2:56:04<2:18:22, 19.17s/it]

(array([], dtype=int64),)

 56%|█████▋    | 561/993 [2:56:23<2:18:19, 19.21s/it]

(array([], dtype=int64),)

 57%|█████▋    | 562/993 [2:56:46<2:25:53, 20.31s/it]

(array([], dtype=int64),)

 57%|█████▋    | 563/993 [2:57:06<2:24:52, 20.22s/it]

(array([], dtype=int64),)

 57%|█████▋    | 564/993 [2:57:27<2:25:23, 20.33s/it]

(array([], dtype=int64),)

 57%|█████▋    | 565/993 [2:57:49<2:29:37, 20.98s/it]

(array([], dtype=int64),)

 57%|█████▋    | 566/993 [2:58:06<2:18:58, 19.53s/it]

(array([], dtype=int64),)

 57%|█████▋    | 567/993 [2:58:25<2:18:51, 19.56s/it]

(array([], dtype=int64),)

 57%|█████▋    | 568/993 [2:58:44<2:16:16, 19.24s/it]

(array([], dtype=int64),)

 57%|█████▋    | 569/993 [2:59:03<2:17:00, 19.39s/it]

(array([], dtype=int64),)

 57%|█████▋    | 570/993 [2:59:33<2:38:43, 22.51s/it]

(array([], dtype=int64),)

 58%|█████▊    | 571/993 [3:00:09<3:07:12, 26.62s/it]

(array([], dtype=int64),)

 58%|█████▊    | 572/993 [3:00:33<2:59:52, 25.64s/it]

(array([], dtype=int64),)

 58%|█████▊    | 573/993 [3:00:54<2:51:04, 24.44s/it]

(array([], dtype=int64),)

 58%|█████▊    | 574/993 [3:01:13<2:38:31, 22.70s/it]

(array([], dtype=int64),)

 58%|█████▊    | 575/993 [3:01:32<2:30:11, 21.56s/it]

(array([], dtype=int64),)

 58%|█████▊    | 576/993 [3:01:55<2:31:58, 21.87s/it]

(array([], dtype=int64),)

 58%|█████▊    | 577/993 [3:02:21<2:40:08, 23.10s/it]

(array([], dtype=int64),)

 58%|█████▊    | 578/993 [3:02:56<3:05:20, 26.80s/it]

(array([], dtype=int64),)

 58%|█████▊    | 579/993 [3:03:30<3:19:07, 28.86s/it]

(array([], dtype=int64),)

 59%|█████▊    | 582/993 [3:04:04<2:41:43, 23.61s/it]

(array([], dtype=int64),)

 59%|█████▉    | 589/993 [3:04:21<1:56:23, 17.29s/it]

(array([], dtype=int64),)

 59%|█████▉    | 590/993 [3:04:39<1:56:23, 17.33s/it]

(array([], dtype=int64),)

 60%|█████▉    | 591/993 [3:04:51<1:45:20, 15.72s/it]

(array([], dtype=int64),)

 60%|█████▉    | 593/993 [3:05:14<1:36:54, 14.54s/it]

(array([], dtype=int64),)

 61%|██████    | 601/993 [3:05:43<1:13:26, 11.24s/it]

(array([], dtype=int64),)

 61%|██████    | 602/993 [3:06:09<1:42:20, 15.71s/it]

(array([], dtype=int64),)

 61%|██████    | 603/993 [3:06:33<1:58:27, 18.22s/it]

(array([], dtype=int64),)

 61%|██████    | 604/993 [3:06:51<1:57:41, 18.15s/it]

(array([], dtype=int64),)

 61%|██████    | 605/993 [3:07:17<2:13:00, 20.57s/it]

(array([], dtype=int64),)

 61%|██████    | 606/993 [3:07:42<2:20:40, 21.81s/it]

(array([], dtype=int64),)

 61%|██████    | 607/993 [3:08:06<2:24:10, 22.41s/it]

(array([], dtype=int64),)

 61%|██████    | 608/993 [3:08:26<2:18:57, 21.65s/it]

(array([], dtype=int64),)

 61%|██████▏   | 609/993 [3:08:47<2:18:24, 21.63s/it]

(array([], dtype=int64),)

 61%|██████▏   | 610/993 [3:09:08<2:15:54, 21.29s/it]

(array([], dtype=int64),)

 62%|██████▏   | 611/993 [3:09:31<2:18:54, 21.82s/it]

(array([], dtype=int64),)

 62%|██████▏   | 612/993 [3:09:56<2:25:40, 22.94s/it]

(array([], dtype=int64),)

 62%|██████▏   | 613/993 [3:10:20<2:26:37, 23.15s/it]

(array([], dtype=int64),)

 62%|██████▏   | 614/993 [3:10:42<2:24:17, 22.84s/it]

(array([], dtype=int64),)

 62%|██████▏   | 615/993 [3:11:06<2:25:35, 23.11s/it]

(array([], dtype=int64),)

 62%|██████▏   | 616/993 [3:11:34<2:35:20, 24.72s/it]

(array([], dtype=int64),)

 62%|██████▏   | 617/993 [3:11:57<2:30:52, 24.08s/it]

(array([], dtype=int64),)

 62%|██████▏   | 618/993 [3:12:20<2:29:09, 23.87s/it]

(array([], dtype=int64),)

 62%|██████▏   | 619/993 [3:12:38<2:17:15, 22.02s/it]

(array([], dtype=int64),)

 62%|██████▏   | 620/993 [3:12:57<2:10:47, 21.04s/it]

(array([], dtype=int64),)

 63%|██████▎   | 621/993 [3:13:21<2:16:14, 21.97s/it]

(array([], dtype=int64),)

 63%|██████▎   | 622/993 [3:13:57<2:41:57, 26.19s/it]

(array([], dtype=int64),)

 63%|██████▎   | 623/993 [3:14:23<2:40:58, 26.10s/it]

(array([], dtype=int64),)

 63%|██████▎   | 624/993 [3:15:01<3:03:10, 29.78s/it]

(array([], dtype=int64),)

 63%|██████▎   | 625/993 [3:15:21<2:44:42, 26.86s/it]

(array([], dtype=int64),)

 63%|██████▎   | 626/993 [3:15:40<2:29:04, 24.37s/it]

(array([], dtype=int64),)

 63%|██████▎   | 627/993 [3:15:58<2:17:34, 22.55s/it]

(array([], dtype=int64),)

 63%|██████▎   | 628/993 [3:16:20<2:16:52, 22.50s/it]

(array([], dtype=int64),)

 63%|██████▎   | 629/993 [3:16:40<2:12:09, 21.78s/it]

(array([], dtype=int64),)

 63%|██████▎   | 630/993 [3:16:58<2:03:44, 20.45s/it]

(array([], dtype=int64),)

 64%|██████▎   | 631/993 [3:17:13<1:53:49, 18.87s/it]

(array([], dtype=int64),)

 64%|██████▎   | 632/993 [3:17:28<1:46:26, 17.69s/it]

(array([], dtype=int64),)

 64%|██████▎   | 633/993 [3:17:42<1:39:24, 16.57s/it]

(array([], dtype=int64),)

 64%|██████▍   | 634/993 [3:17:57<1:35:57, 16.04s/it]

(array([], dtype=int64),)

 64%|██████▍   | 635/993 [3:18:15<1:39:12, 16.63s/it]

(array([], dtype=int64),)

 64%|██████▍   | 636/993 [3:18:45<2:02:27, 20.58s/it]

(array([], dtype=int64),)

 64%|██████▍   | 637/993 [3:19:05<2:02:34, 20.66s/it]

(array([], dtype=int64),)

 64%|██████▍   | 638/993 [3:19:26<2:01:58, 20.62s/it]

(array([], dtype=int64),)

 64%|██████▍   | 639/993 [3:19:44<1:56:52, 19.81s/it]

(array([], dtype=int64),)

 64%|██████▍   | 640/993 [3:20:03<1:56:21, 19.78s/it]

(array([], dtype=int64),)

 65%|██████▍   | 641/993 [3:20:24<1:57:06, 19.96s/it]

(array([], dtype=int64),)

 65%|██████▍   | 642/993 [3:20:41<1:51:03, 18.98s/it]

(array([], dtype=int64),)

 65%|██████▍   | 643/993 [3:20:59<1:48:58, 18.68s/it]

(array([], dtype=int64),)

 65%|██████▍   | 644/993 [3:21:17<1:48:43, 18.69s/it]

(array([], dtype=int64),)

 65%|██████▍   | 645/993 [3:21:36<1:48:29, 18.71s/it]

(array([], dtype=int64),)

 65%|██████▌   | 646/993 [3:21:56<1:50:10, 19.05s/it]

(array([], dtype=int64),)

 65%|██████▌   | 647/993 [3:22:17<1:53:12, 19.63s/it]

(array([], dtype=int64),)

 65%|██████▌   | 648/993 [3:22:36<1:51:30, 19.39s/it]

(array([], dtype=int64),)

 65%|██████▌   | 649/993 [3:22:54<1:49:07, 19.03s/it]

(array([], dtype=int64),)

 65%|██████▌   | 650/993 [3:23:12<1:46:59, 18.71s/it]

(array([], dtype=int64),)

 66%|██████▌   | 651/993 [3:23:31<1:46:45, 18.73s/it]

(array([], dtype=int64),)

 66%|██████▌   | 652/993 [3:23:50<1:47:34, 18.93s/it]

(array([], dtype=int64),)

 66%|██████▌   | 653/993 [3:24:07<1:44:40, 18.47s/it]

(array([], dtype=int64),)

 66%|██████▌   | 654/993 [3:24:26<1:44:08, 18.43s/it]

(array([], dtype=int64),)

 66%|██████▌   | 655/993 [3:24:44<1:43:54, 18.45s/it]

(array([], dtype=int64),)

 66%|██████▌   | 656/993 [3:25:09<1:54:29, 20.39s/it]

(array([], dtype=int64),)

 66%|██████▌   | 657/993 [3:25:27<1:49:41, 19.59s/it]

(array([], dtype=int64),)

 66%|██████▋   | 658/993 [3:25:46<1:47:57, 19.34s/it]

(array([], dtype=int64),)

 66%|██████▋   | 659/993 [3:26:05<1:48:21, 19.47s/it]

(array([], dtype=int64),)

 67%|██████▋   | 661/993 [3:26:23<1:30:21, 16.33s/it]

(array([], dtype=int64),)

 67%|██████▋   | 662/993 [3:26:40<1:30:27, 16.40s/it]

(array([], dtype=int64),)

 67%|██████▋   | 663/993 [3:27:05<1:44:20, 18.97s/it]

(array([], dtype=int64),)

 67%|██████▋   | 664/993 [3:27:21<1:39:40, 18.18s/it]

(array([], dtype=int64),)

 67%|██████▋   | 665/993 [3:27:37<1:35:28, 17.46s/it]

(array([], dtype=int64),)

 67%|██████▋   | 666/993 [3:28:02<1:46:37, 19.56s/it]

(array([], dtype=int64),)

 67%|██████▋   | 667/993 [3:28:17<1:38:58, 18.22s/it]

(array([], dtype=int64),)

 67%|██████▋   | 668/993 [3:28:32<1:34:18, 17.41s/it]

(array([], dtype=int64),)

 67%|██████▋   | 669/993 [3:28:49<1:33:15, 17.27s/it]

(array([], dtype=int64),)

 67%|██████▋   | 670/993 [3:29:09<1:36:54, 18.00s/it]

(array([], dtype=int64),)

 68%|██████▊   | 671/993 [3:29:25<1:33:41, 17.46s/it]

(array([], dtype=int64),)

 68%|██████▊   | 672/993 [3:29:43<1:34:55, 17.74s/it]

(array([], dtype=int64),)

 68%|██████▊   | 673/993 [3:30:03<1:37:20, 18.25s/it]

(array([], dtype=int64),)

 68%|██████▊   | 674/993 [3:30:21<1:37:15, 18.29s/it]

(array([], dtype=int64),)

 68%|██████▊   | 675/993 [3:30:39<1:36:15, 18.16s/it]

(array([], dtype=int64),)

 68%|██████▊   | 676/993 [3:30:57<1:35:07, 18.01s/it]

(array([], dtype=int64),)

 68%|██████▊   | 677/993 [3:31:15<1:35:35, 18.15s/it]

(array([], dtype=int64),)

 68%|██████▊   | 678/993 [3:31:32<1:33:54, 17.89s/it]

(array([], dtype=int64),)

 68%|██████▊   | 679/993 [3:31:59<1:46:25, 20.34s/it]

(array([], dtype=int64),)

 68%|██████▊   | 680/993 [3:32:22<1:51:32, 21.38s/it]

(array([], dtype=int64),)

 69%|██████▊   | 681/993 [3:32:42<1:47:49, 20.74s/it]

(array([], dtype=int64),)

 69%|██████▊   | 682/993 [3:32:58<1:41:24, 19.56s/it]

(array([], dtype=int64),)

 69%|██████▉   | 683/993 [3:33:17<1:39:20, 19.23s/it]

(array([], dtype=int64),)

 69%|██████▉   | 684/993 [3:33:34<1:36:13, 18.68s/it]

(array([], dtype=int64),)

 69%|██████▉   | 685/993 [3:33:51<1:32:49, 18.08s/it]

(array([], dtype=int64),)

 69%|██████▉   | 686/993 [3:34:07<1:29:27, 17.48s/it]

(array([], dtype=int64),)

 69%|██████▉   | 687/993 [3:34:40<1:52:55, 22.14s/it]

(array([], dtype=int64),)

 69%|██████▉   | 688/993 [3:34:58<1:45:37, 20.78s/it]

(array([], dtype=int64),)

 69%|██████▉   | 690/993 [3:35:13<1:25:13, 16.88s/it]

(array([], dtype=int64),)

 70%|██████▉   | 691/993 [3:35:35<1:33:04, 18.49s/it]

(array([], dtype=int64),)

 70%|██████▉   | 692/993 [3:36:01<1:44:07, 20.75s/it]

(array([], dtype=int64),)

 70%|██████▉   | 693/993 [3:36:28<1:51:52, 22.37s/it]

(array([], dtype=int64),)

 70%|██████▉   | 694/993 [3:36:54<1:56:51, 23.45s/it]

(array([], dtype=int64),)

 70%|██████▉   | 695/993 [3:37:14<1:52:37, 22.68s/it]

(array([], dtype=int64),)

 70%|███████   | 696/993 [3:37:48<2:08:21, 25.93s/it]

(array([], dtype=int64),)

 70%|███████   | 697/993 [3:38:11<2:03:33, 25.05s/it]

(array([], dtype=int64),)

 70%|███████   | 698/993 [3:38:29<1:53:17, 23.04s/it]

(array([], dtype=int64),)

 70%|███████   | 700/993 [3:38:58<1:40:05, 20.50s/it]

(array([], dtype=int64),)

 71%|███████   | 701/993 [3:39:26<1:49:18, 22.46s/it]

(array([], dtype=int64),)

 71%|███████   | 702/993 [3:39:45<1:44:24, 21.53s/it]

(array([], dtype=int64),)

 71%|███████   | 703/993 [3:40:06<1:43:50, 21.48s/it]

(array([], dtype=int64),)

 71%|███████   | 704/993 [3:40:24<1:38:05, 20.36s/it]

(array([], dtype=int64),)

 71%|███████   | 705/993 [3:40:42<1:34:05, 19.60s/it]

(array([], dtype=int64),)

 71%|███████   | 706/993 [3:41:02<1:33:55, 19.63s/it]

(array([], dtype=int64),)

 71%|███████   | 707/993 [3:41:19<1:30:19, 18.95s/it]

(array([], dtype=int64),)

 71%|███████▏  | 708/993 [3:41:37<1:29:16, 18.79s/it]

(array([], dtype=int64),)

 71%|███████▏  | 709/993 [3:42:06<1:43:35, 21.88s/it]

(array([], dtype=int64),)

 72%|███████▏  | 710/993 [3:42:45<2:06:17, 26.77s/it]

(array([], dtype=int64),)

 72%|███████▏  | 711/993 [3:43:06<1:58:53, 25.30s/it]

(array([], dtype=int64),)

 72%|███████▏  | 712/993 [3:43:27<1:52:14, 23.96s/it]

(array([], dtype=int64),)

 72%|███████▏  | 713/993 [3:43:45<1:42:28, 21.96s/it]

(array([], dtype=int64),)

 72%|███████▏  | 714/993 [3:43:59<1:32:10, 19.82s/it]

(array([], dtype=int64),)

 72%|███████▏  | 715/993 [3:44:21<1:33:45, 20.23s/it]

(array([], dtype=int64),)

 72%|███████▏  | 716/993 [3:44:40<1:32:22, 20.01s/it]

(array([], dtype=int64),)

 72%|███████▏  | 717/993 [3:45:05<1:38:10, 21.34s/it]

(array([], dtype=int64),)

 72%|███████▏  | 718/993 [3:45:24<1:34:56, 20.71s/it]

(array([], dtype=int64),)

 72%|███████▏  | 719/993 [3:45:44<1:33:56, 20.57s/it]

(array([], dtype=int64),)

 73%|███████▎  | 720/993 [3:46:14<1:46:57, 23.51s/it]

(array([], dtype=int64),)

 73%|███████▎  | 721/993 [3:46:38<1:47:12, 23.65s/it]

(array([], dtype=int64),)

 73%|███████▎  | 722/993 [3:47:00<1:43:59, 23.02s/it]

(array([], dtype=int64),)

 73%|███████▎  | 723/993 [3:47:21<1:41:13, 22.49s/it]

(array([], dtype=int64),)

 73%|███████▎  | 724/993 [3:47:46<1:44:04, 23.22s/it]

(array([], dtype=int64),)

 73%|███████▎  | 725/993 [3:48:10<1:45:05, 23.53s/it]

(array([], dtype=int64),)

 73%|███████▎  | 726/993 [3:48:34<1:44:46, 23.54s/it]

(array([], dtype=int64),)

 73%|███████▎  | 727/993 [3:49:00<1:47:51, 24.33s/it]

(array([], dtype=int64),)

 73%|███████▎  | 728/993 [3:49:29<1:53:14, 25.64s/it]

(array([], dtype=int64),)

 73%|███████▎  | 729/993 [3:49:49<1:46:04, 24.11s/it]

(array([], dtype=int64),)

 74%|███████▎  | 730/993 [3:50:07<1:37:44, 22.30s/it]

(array([], dtype=int64),)

 74%|███████▎  | 731/993 [3:50:25<1:30:49, 20.80s/it]

(array([], dtype=int64),)

 74%|███████▎  | 732/993 [3:50:41<1:25:13, 19.59s/it]

(array([], dtype=int64),)

 74%|███████▍  | 733/993 [3:50:59<1:22:41, 19.08s/it]

(array([], dtype=int64),)

 74%|███████▍  | 734/993 [3:51:18<1:21:31, 18.88s/it]

(array([], dtype=int64),)

 74%|███████▍  | 735/993 [3:51:37<1:21:58, 19.06s/it]

(array([], dtype=int64),)

 74%|███████▍  | 736/993 [3:51:53<1:16:56, 17.96s/it]

(array([], dtype=int64),)

 74%|███████▍  | 737/993 [3:52:15<1:21:44, 19.16s/it]

(array([], dtype=int64),)

 74%|███████▍  | 739/993 [3:52:42<1:13:53, 17.45s/it]

(array([], dtype=int64),)

 75%|███████▍  | 741/993 [3:53:04<1:05:19, 15.55s/it]

(array([], dtype=int64),)

 75%|███████▍  | 742/993 [3:53:23<1:09:45, 16.67s/it]

(array([], dtype=int64),)

 75%|███████▍  | 743/993 [3:53:42<1:12:34, 17.42s/it]

(array([], dtype=int64),)

 75%|███████▍  | 744/993 [3:54:11<1:26:46, 20.91s/it]

(array([], dtype=int64),)

 75%|███████▌  | 745/993 [3:54:31<1:25:21, 20.65s/it]

(array([], dtype=int64),)

 75%|███████▌  | 747/993 [3:54:49<1:10:24, 17.17s/it]

(array([], dtype=int64),)

 75%|███████▌  | 748/993 [3:55:10<1:14:27, 18.23s/it]

(array([], dtype=int64),)

 76%|███████▌  | 750/993 [3:55:25<1:01:00, 15.07s/it]

(array([], dtype=int64),)

 76%|███████▌  | 751/993 [3:55:47<1:09:05, 17.13s/it]

(array([], dtype=int64),)

 76%|███████▌  | 752/993 [3:56:28<1:36:42, 24.08s/it]

(array([], dtype=int64),)

 76%|███████▌  | 753/993 [3:56:57<1:42:00, 25.50s/it]

(array([], dtype=int64),)

 76%|███████▌  | 754/993 [3:57:10<1:27:38, 22.00s/it]

(array([], dtype=int64),)

 76%|███████▌  | 755/993 [3:57:33<1:28:28, 22.31s/it]

(array([], dtype=int64),)

 76%|███████▌  | 756/993 [3:58:07<1:41:50, 25.78s/it]

(array([], dtype=int64),)

 76%|███████▌  | 757/993 [3:58:39<1:48:14, 27.52s/it]

(array([], dtype=int64),)

 76%|███████▋  | 758/993 [3:59:12<1:54:43, 29.29s/it]

(array([], dtype=int64),)

 76%|███████▋  | 759/993 [3:59:34<1:45:27, 27.04s/it]

(array([], dtype=int64),)

 77%|███████▋  | 760/993 [3:59:53<1:35:20, 24.55s/it]

(array([], dtype=int64),)

 77%|███████▋  | 761/993 [4:00:15<1:32:35, 23.94s/it]

(array([], dtype=int64),)

 77%|███████▋  | 762/993 [4:00:33<1:24:47, 22.02s/it]

(array([], dtype=int64),)

 77%|███████▋  | 763/993 [4:00:58<1:27:38, 22.86s/it]

(array([], dtype=int64),)

 77%|███████▋  | 764/993 [4:01:35<1:44:05, 27.27s/it]

(array([], dtype=int64),)

 77%|███████▋  | 765/993 [4:01:57<1:37:46, 25.73s/it]

(array([], dtype=int64),)

 77%|███████▋  | 766/993 [4:02:20<1:33:55, 24.83s/it]

(array([], dtype=int64),)

 77%|███████▋  | 767/993 [4:02:48<1:37:07, 25.79s/it]

(array([], dtype=int64),)

 77%|███████▋  | 768/993 [4:03:05<1:26:31, 23.07s/it]

(array([], dtype=int64),)

 77%|███████▋  | 769/993 [4:03:18<1:15:13, 20.15s/it]

(array([], dtype=int64),)

 78%|███████▊  | 770/993 [4:03:37<1:13:28, 19.77s/it]

(array([], dtype=int64),)

 78%|███████▊  | 771/993 [4:04:00<1:16:33, 20.69s/it]

(array([], dtype=int64),)

 78%|███████▊  | 772/993 [4:04:19<1:14:33, 20.24s/it]

(array([], dtype=int64),)

 78%|███████▊  | 775/993 [4:04:44<1:00:24, 16.62s/it]

(array([], dtype=int64),)

 78%|███████▊  | 777/993 [4:04:59<50:11, 13.94s/it]

(array([], dtype=int64),)

 78%|███████▊  | 778/993 [4:05:34<1:12:59, 20.37s/it]

(array([], dtype=int64),)

 78%|███████▊  | 779/993 [4:05:52<1:09:18, 19.43s/it]

(array([], dtype=int64),)

 79%|███████▊  | 780/993 [4:06:12<1:10:04, 19.74s/it]

(array([], dtype=int64),)

 79%|███████▊  | 781/993 [4:06:30<1:08:17, 19.33s/it]

(array([], dtype=int64),)

 79%|███████▉  | 782/993 [4:06:54<1:11:52, 20.44s/it]

(array([], dtype=int64),)

 79%|███████▉  | 783/993 [4:07:26<1:24:17, 24.09s/it]

(array([], dtype=int64),)

 79%|███████▉  | 784/993 [4:07:51<1:24:54, 24.38s/it]

(array([], dtype=int64),)

 79%|███████▉  | 785/993 [4:08:16<1:24:54, 24.49s/it]

(array([], dtype=int64),)

 79%|███████▉  | 786/993 [4:08:42<1:25:56, 24.91s/it]

(array([], dtype=int64),)

 79%|███████▉  | 787/993 [4:09:09<1:27:23, 25.45s/it]

(array([], dtype=int64),)

 79%|███████▉  | 788/993 [4:09:36<1:28:37, 25.94s/it]

(array([], dtype=int64),)

 79%|███████▉  | 789/993 [4:10:07<1:33:53, 27.61s/it]

(array([], dtype=int64),)

 80%|███████▉  | 790/993 [4:10:28<1:26:41, 25.62s/it]

(array([], dtype=int64),)

 80%|███████▉  | 791/993 [4:10:49<1:21:13, 24.12s/it]

(array([], dtype=int64),)

 80%|███████▉  | 792/993 [4:11:11<1:18:57, 23.57s/it]

(array([], dtype=int64),)

 80%|███████▉  | 793/993 [4:11:31<1:14:52, 22.46s/it]

(array([], dtype=int64),)

 80%|███████▉  | 794/993 [4:11:54<1:14:59, 22.61s/it]

(array([], dtype=int64),)

 80%|████████  | 795/993 [4:12:16<1:13:51, 22.38s/it]

(array([], dtype=int64),)

 80%|████████  | 796/993 [4:12:35<1:10:22, 21.43s/it]

(array([], dtype=int64),)

 80%|████████  | 797/993 [4:12:49<1:02:35, 19.16s/it]

(array([], dtype=int64),)

 80%|████████  | 798/993 [4:13:10<1:04:41, 19.90s/it]

(array([], dtype=int64),)

 80%|████████  | 799/993 [4:13:31<1:05:22, 20.22s/it]

(array([], dtype=int64),)

 81%|████████  | 800/993 [4:13:52<1:05:45, 20.44s/it]

(array([], dtype=int64),)

 81%|████████  | 801/993 [4:14:08<1:00:26, 18.89s/it]

(array([], dtype=int64),)

 81%|████████  | 802/993 [4:14:26<59:20, 18.64s/it]

(array([], dtype=int64),)

 81%|████████  | 803/993 [4:14:44<58:18, 18.41s/it]

(array([], dtype=int64),)

 81%|████████  | 804/993 [4:15:03<58:31, 18.58s/it]

(array([], dtype=int64),)

 81%|████████  | 805/993 [4:15:22<58:52, 18.79s/it]

(array([], dtype=int64),)

 81%|████████  | 806/993 [4:15:36<54:31, 17.50s/it]

(array([], dtype=int64),)

 81%|████████▏ | 807/993 [4:15:55<55:22, 17.87s/it]

(array([], dtype=int64),)

 81%|████████▏ | 808/993 [4:16:15<57:20, 18.60s/it]

(array([], dtype=int64),)

 81%|████████▏ | 809/993 [4:16:39<1:01:55, 20.20s/it]

(array([], dtype=int64),)

 82%|████████▏ | 810/993 [4:17:00<1:02:06, 20.36s/it]

(array([], dtype=int64),)

 82%|████████▏ | 811/993 [4:17:17<58:38, 19.33s/it]

(array([], dtype=int64),)

 82%|████████▏ | 812/993 [4:17:39<1:00:35, 20.08s/it]

(array([], dtype=int64),)

 82%|████████▏ | 813/993 [4:17:56<57:57, 19.32s/it]

(array([], dtype=int64),)

 82%|████████▏ | 814/993 [4:18:16<58:06, 19.48s/it]

(array([], dtype=int64),)

 82%|████████▏ | 815/993 [4:18:34<56:13, 18.95s/it]

(array([], dtype=int64),)

 82%|████████▏ | 816/993 [4:18:57<59:54, 20.31s/it]

(array([], dtype=int64),)

 82%|████████▏ | 817/993 [4:19:21<1:02:56, 21.46s/it]

(array([], dtype=int64),)

 82%|████████▏ | 818/993 [4:19:45<1:04:39, 22.17s/it]

(array([], dtype=int64),)

 82%|████████▏ | 819/993 [4:20:14<1:10:15, 24.23s/it]

(array([], dtype=int64),)

 83%|████████▎ | 820/993 [4:20:42<1:12:38, 25.19s/it]

(array([], dtype=int64),)

 83%|████████▎ | 821/993 [4:21:09<1:13:38, 25.69s/it]

(array([], dtype=int64),)

 83%|████████▎ | 822/993 [4:21:27<1:07:23, 23.65s/it]

(array([], dtype=int64),)

 83%|████████▎ | 823/993 [4:21:45<1:01:54, 21.85s/it]

(array([], dtype=int64),)

 83%|████████▎ | 824/993 [4:22:05<59:26, 21.10s/it]

(array([], dtype=int64),)

 83%|████████▎ | 825/993 [4:22:26<59:11, 21.14s/it]

(array([], dtype=int64),)

 83%|████████▎ | 826/993 [4:22:47<58:52, 21.15s/it]

(array([], dtype=int64),)

 83%|████████▎ | 827/993 [4:23:05<55:43, 20.14s/it]

(array([], dtype=int64),)

 83%|████████▎ | 828/993 [4:23:25<55:41, 20.25s/it]

(array([], dtype=int64),)

 83%|████████▎ | 829/993 [4:23:46<55:41, 20.37s/it]

(array([], dtype=int64),)

 84%|████████▎ | 830/993 [4:24:07<55:45, 20.53s/it]

(array([], dtype=int64),)

 84%|████████▎ | 831/993 [4:24:29<56:39, 20.98s/it]

(array([], dtype=int64),)

 84%|████████▍ | 832/993 [4:24:52<57:59, 21.61s/it]

(array([], dtype=int64),)

 84%|████████▍ | 833/993 [4:25:13<57:16, 21.48s/it]

(array([], dtype=int64),)

 84%|████████▍ | 834/993 [4:25:34<56:37, 21.37s/it]

(array([], dtype=int64),)

 84%|████████▍ | 835/993 [4:25:55<55:54, 21.23s/it]

(array([], dtype=int64),)

 84%|████████▍ | 836/993 [4:26:10<50:23, 19.26s/it]

(array([], dtype=int64),)

 84%|████████▍ | 837/993 [4:26:28<49:05, 18.88s/it]

(array([], dtype=int64),)

 84%|████████▍ | 838/993 [4:26:48<49:33, 19.19s/it]

(array([], dtype=int64),)

 84%|████████▍ | 839/993 [4:27:05<47:57, 18.68s/it]

(array([], dtype=int64),)

 85%|████████▍ | 840/993 [4:27:27<50:26, 19.78s/it]

(array([], dtype=int64),)

 85%|████████▍ | 841/993 [4:27:44<47:41, 18.82s/it]

(array([], dtype=int64),)

 85%|████████▍ | 842/993 [4:28:04<48:12, 19.15s/it]

(array([], dtype=int64),)

 85%|████████▍ | 843/993 [4:28:24<48:53, 19.56s/it]

(array([], dtype=int64),)

 85%|████████▍ | 844/993 [4:28:44<48:39, 19.59s/it]

(array([], dtype=int64),)

 85%|████████▌ | 845/993 [4:29:04<48:47, 19.78s/it]

(array([], dtype=int64),)

 85%|████████▌ | 846/993 [4:29:19<44:46, 18.27s/it]

(array([], dtype=int64),)

 85%|████████▌ | 847/993 [4:29:40<46:20, 19.05s/it]

(array([], dtype=int64),)

 85%|████████▌ | 848/993 [4:30:00<47:03, 19.47s/it]

(array([], dtype=int64),)

 85%|████████▌ | 849/993 [4:30:22<48:24, 20.17s/it]

(array([], dtype=int64),)

 86%|████████▌ | 850/993 [4:30:41<46:56, 19.69s/it]

(array([], dtype=int64),)

 86%|████████▌ | 851/993 [4:31:07<51:30, 21.77s/it]

(array([], dtype=int64),)

 86%|████████▌ | 852/993 [4:31:32<53:18, 22.68s/it]

(array([], dtype=int64),)

 86%|████████▌ | 853/993 [4:32:20<1:10:41, 30.30s/it]

(array([], dtype=int64),)

 86%|████████▌ | 854/993 [4:32:38<1:01:09, 26.40s/it]

(array([], dtype=int64),)

 86%|████████▌ | 855/993 [4:32:55<54:50, 23.84s/it]

(array([], dtype=int64),)

 86%|████████▌ | 856/993 [4:33:17<52:38, 23.06s/it]

(array([], dtype=int64),)

 86%|████████▋ | 857/993 [4:33:33<47:45, 21.07s/it]

(array([], dtype=int64),)

 86%|████████▋ | 858/993 [4:33:51<45:27, 20.20s/it]

(array([], dtype=int64),)

 87%|████████▋ | 859/993 [4:34:12<45:26, 20.35s/it]

(array([], dtype=int64),)

 87%|████████▋ | 860/993 [4:34:30<43:32, 19.65s/it]

(array([], dtype=int64),)

 87%|████████▋ | 861/993 [4:34:47<41:41, 18.95s/it]

(array([], dtype=int64),)

 87%|████████▋ | 862/993 [4:35:09<43:02, 19.71s/it]

(array([], dtype=int64),)

 87%|████████▋ | 863/993 [4:35:30<43:31, 20.09s/it]

(array([], dtype=int64),)

 87%|████████▋ | 864/993 [4:35:48<41:55, 19.50s/it]

(array([], dtype=int64),)

 87%|████████▋ | 865/993 [4:36:07<41:36, 19.51s/it]

(array([], dtype=int64),)

 87%|████████▋ | 866/993 [4:36:26<40:34, 19.17s/it]

(array([], dtype=int64),)

 87%|████████▋ | 867/993 [4:36:44<39:54, 19.00s/it]

(array([], dtype=int64),)

 87%|████████▋ | 868/993 [4:37:05<40:17, 19.34s/it]

(array([], dtype=int64),)

 88%|████████▊ | 869/993 [4:37:26<41:19, 19.99s/it]

(array([], dtype=int64),)

 88%|████████▊ | 870/993 [4:37:44<39:23, 19.21s/it]

(array([], dtype=int64),)

 88%|████████▊ | 871/993 [4:38:03<39:19, 19.34s/it]

(array([], dtype=int64),)

 88%|████████▊ | 872/993 [4:38:22<38:32, 19.11s/it]

(array([], dtype=int64),)

 88%|████████▊ | 873/993 [4:38:38<36:44, 18.37s/it]

(array([], dtype=int64),)

 88%|████████▊ | 874/993 [4:39:07<42:47, 21.57s/it]

(array([], dtype=int64),)

 88%|████████▊ | 875/993 [4:39:27<41:23, 21.05s/it]

(array([], dtype=int64),)

 88%|████████▊ | 876/993 [4:39:43<38:04, 19.52s/it]

(array([], dtype=int64),)

 88%|████████▊ | 877/993 [4:39:59<35:41, 18.46s/it]

(array([], dtype=int64),)

 88%|████████▊ | 878/993 [4:40:20<36:29, 19.04s/it]

(array([], dtype=int64),)

 89%|████████▊ | 879/993 [4:40:40<37:07, 19.54s/it]

(array([], dtype=int64),)

 89%|████████▊ | 880/993 [4:40:59<36:32, 19.40s/it]

(array([], dtype=int64),)

 89%|████████▊ | 881/993 [4:41:20<36:52, 19.75s/it]

(array([], dtype=int64),)

 89%|████████▉ | 882/993 [4:41:48<41:07, 22.23s/it]

(array([], dtype=int64),)

 89%|████████▉ | 883/993 [4:42:15<43:22, 23.66s/it]

(array([], dtype=int64),)

 89%|████████▉ | 884/993 [4:42:37<42:02, 23.14s/it]

(array([], dtype=int64),)

 89%|████████▉ | 885/993 [4:42:58<40:36, 22.56s/it]

(array([], dtype=int64),)

 89%|████████▉ | 886/993 [4:43:19<39:07, 21.94s/it]

(array([], dtype=int64),)

 89%|████████▉ | 887/993 [4:43:38<37:27, 21.20s/it]

(array([], dtype=int64),)

 89%|████████▉ | 888/993 [4:43:59<37:12, 21.27s/it]

(array([], dtype=int64),)

 90%|████████▉ | 889/993 [4:44:17<34:56, 20.16s/it]

(array([], dtype=int64),)

 90%|████████▉ | 890/993 [4:44:37<34:16, 19.97s/it]

(array([], dtype=int64),)

 90%|████████▉ | 891/993 [4:44:57<34:20, 20.20s/it]

(array([], dtype=int64),)

 90%|████████▉ | 892/993 [4:45:17<33:45, 20.06s/it]

(array([], dtype=int64),)

 90%|████████▉ | 893/993 [4:45:36<32:40, 19.60s/it]

(array([], dtype=int64),)

 90%|█████████ | 894/993 [4:45:53<31:27, 19.07s/it]

(array([], dtype=int64),)

 90%|█████████ | 895/993 [4:46:12<30:54, 18.92s/it]

(array([], dtype=int64),)

 90%|█████████ | 896/993 [4:46:33<31:25, 19.44s/it]

(array([], dtype=int64),)

 90%|█████████ | 897/993 [4:46:50<30:19, 18.96s/it]

(array([], dtype=int64),)

 90%|█████████ | 898/993 [4:47:08<29:19, 18.53s/it]

(array([], dtype=int64),)

 91%|█████████ | 899/993 [4:47:28<29:37, 18.91s/it]

(array([], dtype=int64),)

 91%|█████████ | 900/993 [4:47:44<28:01, 18.08s/it]

(array([], dtype=int64),)

 91%|█████████ | 901/993 [4:48:03<28:14, 18.42s/it]

(array([], dtype=int64),)

 91%|█████████ | 902/993 [4:48:23<28:45, 18.96s/it]

(array([], dtype=int64),)

 91%|█████████ | 903/993 [4:48:42<28:18, 18.87s/it]

(array([], dtype=int64),)

 91%|█████████ | 904/993 [4:48:57<26:25, 17.82s/it]

(array([], dtype=int64),)

 91%|█████████ | 905/993 [4:49:15<26:01, 17.75s/it]

(array([], dtype=int64),)

 91%|█████████ | 906/993 [4:49:33<26:03, 17.98s/it]

(array([], dtype=int64),)

 91%|█████████▏| 907/993 [4:49:52<26:01, 18.16s/it]

(array([], dtype=int64),)

 91%|█████████▏| 908/993 [4:50:14<27:09, 19.17s/it]

(array([], dtype=int64),)

 92%|█████████▏| 909/993 [4:50:30<25:31, 18.23s/it]

(array([], dtype=int64),)

 92%|█████████▏| 910/993 [4:50:48<25:19, 18.31s/it]

(array([], dtype=int64),)

 92%|█████████▏| 911/993 [4:51:08<25:43, 18.82s/it]

(array([], dtype=int64),)

 92%|█████████▏| 912/993 [4:51:28<25:39, 19.01s/it]

(array([], dtype=int64),)

 92%|█████████▏| 913/993 [4:51:44<24:19, 18.24s/it]

(array([], dtype=int64),)

 92%|█████████▏| 914/993 [4:52:07<25:45, 19.57s/it]

(array([], dtype=int64),)

 92%|█████████▏| 915/993 [4:52:30<26:56, 20.72s/it]

(array([], dtype=int64),)

 92%|█████████▏| 916/993 [4:52:56<28:29, 22.21s/it]

(array([], dtype=int64),)

 92%|█████████▏| 917/993 [4:53:23<30:10, 23.83s/it]

(array([], dtype=int64),)

 92%|█████████▏| 918/993 [4:53:44<28:25, 22.74s/it]

(array([], dtype=int64),)

 93%|█████████▎| 919/993 [4:54:07<28:11, 22.86s/it]

(array([], dtype=int64),)

 93%|█████████▎| 920/993 [4:54:24<25:47, 21.20s/it]

(array([], dtype=int64),)

 93%|█████████▎| 921/993 [4:54:41<23:58, 19.98s/it]

(array([], dtype=int64),)

 93%|█████████▎| 922/993 [4:54:59<22:55, 19.37s/it]

(array([], dtype=int64),)

 93%|█████████▎| 923/993 [4:55:20<22:57, 19.68s/it]

(array([], dtype=int64),)

 93%|█████████▎| 924/993 [4:55:36<21:35, 18.78s/it]

(array([], dtype=int64),)

 93%|█████████▎| 925/993 [4:55:55<21:09, 18.67s/it]

(array([], dtype=int64),)

 93%|█████████▎| 926/993 [4:56:15<21:34, 19.32s/it]

(array([], dtype=int64),)

 93%|█████████▎| 927/993 [4:56:34<20:56, 19.04s/it]

(array([], dtype=int64),)

 93%|█████████▎| 928/993 [4:56:53<20:38, 19.06s/it]

(array([], dtype=int64),)

 94%|█████████▎| 929/993 [4:57:11<19:54, 18.67s/it]

(array([], dtype=int64),)

 94%|█████████▎| 930/993 [4:57:29<19:36, 18.67s/it]

(array([], dtype=int64),)

 94%|█████████▍| 931/993 [4:57:50<19:54, 19.27s/it]

(array([], dtype=int64),)

 94%|█████████▍| 932/993 [4:58:08<19:19, 19.01s/it]

(array([], dtype=int64),)

 94%|█████████▍| 933/993 [4:58:30<19:45, 19.76s/it]

(array([], dtype=int64),)

 94%|█████████▍| 934/993 [4:58:51<19:45, 20.09s/it]

(array([], dtype=int64),)

 94%|█████████▍| 935/993 [4:59:10<19:07, 19.78s/it]

(array([], dtype=int64),)

 94%|█████████▍| 936/993 [4:59:28<18:15, 19.23s/it]

(array([], dtype=int64),)

 94%|█████████▍| 937/993 [4:59:48<18:20, 19.66s/it]

(array([], dtype=int64),)

 94%|█████████▍| 938/993 [5:00:06<17:20, 18.93s/it]

(array([], dtype=int64),)

 95%|█████████▍| 939/993 [5:00:27<17:34, 19.53s/it]

(array([], dtype=int64),)

 95%|█████████▍| 940/993 [5:00:46<17:05, 19.34s/it]

(array([], dtype=int64),)

 95%|█████████▍| 941/993 [5:01:03<16:10, 18.66s/it]

(array([], dtype=int64),)

 95%|█████████▍| 943/993 [5:01:22<13:17, 15.94s/it]

(array([], dtype=int64),)

 95%|█████████▌| 944/993 [5:01:42<13:58, 17.11s/it]

(array([], dtype=int64),)

 95%|█████████▌| 945/993 [5:02:01<14:16, 17.83s/it]

(array([], dtype=int64),)

 95%|█████████▌| 946/993 [5:02:22<14:39, 18.72s/it]

(array([], dtype=int64),)

 95%|█████████▌| 947/993 [5:02:43<14:53, 19.42s/it]

(array([], dtype=int64),)

 95%|█████████▌| 948/993 [5:03:02<14:34, 19.43s/it]

(array([], dtype=int64),)

 96%|█████████▌| 949/993 [5:03:23<14:34, 19.89s/it]

(array([], dtype=int64),)

 96%|█████████▌| 950/993 [5:03:51<15:56, 22.24s/it]

(array([], dtype=int64),)

 96%|█████████▌| 951/993 [5:04:15<15:49, 22.60s/it]

(array([], dtype=int64),)

 96%|█████████▌| 952/993 [5:04:41<16:08, 23.63s/it]

(array([], dtype=int64),)

 96%|█████████▌| 953/993 [5:05:04<15:47, 23.68s/it]

(array([], dtype=int64),)

 96%|█████████▌| 954/993 [5:05:18<13:20, 20.52s/it]

(array([], dtype=int64),)

 96%|█████████▌| 955/993 [5:05:38<13:00, 20.54s/it]

(array([], dtype=int64),)

 96%|█████████▋| 956/993 [5:05:56<12:08, 19.69s/it]

(array([], dtype=int64),)

 96%|█████████▋| 957/993 [5:06:16<11:49, 19.70s/it]

(array([], dtype=int64),)

 96%|█████████▋| 958/993 [5:06:32<10:55, 18.73s/it]

(array([], dtype=int64),)

 97%|█████████▋| 959/993 [5:06:42<09:08, 16.12s/it]

(array([], dtype=int64),)

 97%|█████████▋| 961/993 [5:07:01<07:32, 14.15s/it]

(array([], dtype=int64),)

 97%|█████████▋| 962/993 [5:07:16<07:23, 14.31s/it]

(array([], dtype=int64),)

 97%|█████████▋| 963/993 [5:07:33<07:36, 15.22s/it]

(array([], dtype=int64),)

 97%|█████████▋| 964/993 [5:07:49<07:27, 15.43s/it]

(array([], dtype=int64),)

 97%|█████████▋| 965/993 [5:08:09<07:48, 16.75s/it]

(array([], dtype=int64),)

 97%|█████████▋| 966/993 [5:08:19<06:41, 14.88s/it]

(array([], dtype=int64),)

 98%|█████████▊| 972/993 [5:08:39<03:59, 11.39s/it]

(array([], dtype=int64),)

 98%|█████████▊| 973/993 [5:08:57<04:27, 13.39s/it]

(array([], dtype=int64),)

 98%|█████████▊| 974/993 [5:09:15<04:43, 14.91s/it]

(array([], dtype=int64),)

 98%|█████████▊| 975/993 [5:09:35<04:55, 16.43s/it]

(array([], dtype=int64),)

 98%|█████████▊| 976/993 [5:09:54<04:50, 17.06s/it]

(array([], dtype=int64),)

 98%|█████████▊| 977/993 [5:10:14<04:45, 17.84s/it]

(array([], dtype=int64),)

 98%|█████████▊| 978/993 [5:10:32<04:30, 18.05s/it]

(array([], dtype=int64),)

 99%|█████████▊| 979/993 [5:10:49<04:06, 17.59s/it]

(array([], dtype=int64),)

 99%|█████████▊| 980/993 [5:11:06<03:49, 17.65s/it]

(array([], dtype=int64),)

 99%|█████████▉| 981/993 [5:11:24<03:29, 17.50s/it]

(array([], dtype=int64),)

 99%|█████████▉| 982/993 [5:11:52<03:49, 20.90s/it]

(array([], dtype=int64),)

 99%|█████████▉| 983/993 [5:12:12<03:26, 20.66s/it]

(array([], dtype=int64),)

 99%|█████████▉| 984/993 [5:12:30<02:58, 19.86s/it]

(array([], dtype=int64),)

 99%|█████████▉| 985/993 [5:12:48<02:32, 19.06s/it]

(array([], dtype=int64),)

 99%|█████████▉| 986/993 [5:13:05<02:10, 18.69s/it]

(array([], dtype=int64),)

 99%|█████████▉| 987/993 [5:13:27<01:56, 19.39s/it]

(array([], dtype=int64),)

 99%|█████████▉| 988/993 [5:13:44<01:34, 18.91s/it]

(array([], dtype=int64),)

100%|█████████▉| 989/993 [5:14:03<01:15, 18.89s/it]

(array([], dtype=int64),)

100%|█████████▉| 990/993 [5:14:23<00:57, 19.31s/it]

(array([], dtype=int64),)

100%|█████████▉| 991/993 [5:14:47<00:41, 20.61s/it]

(array([], dtype=int64),)

100%|█████████▉| 992/993 [5:15:21<00:24, 24.73s/it]

(array([], dtype=int64),)

100%|██████████| 993/993 [5:15:51<00:00, 26.09s/it]

(array([], dtype=int64),)

100%|██████████| 993/993 [5:16:18<00:00, 19.11s/it]

In [30]:
curve_990_old = curves_points[curves_points['id']==990]

Monkey  Date        Ref Amp  Ref PW  Ref Freq  Ref Dur  Active Channels  Return Channels  Comp PW  Comp Amp
Z       2017-01-20  0        0       0         0        15               32               200      10          132.868287
                                                                                                   20          132.868287
                                                                                                   30          132.868287
                                                                                                   40          132.868287
                                                                                                   50          132.868287
                                                                                                   60          132.868287
                                                                                                   70          132.868287
                                                                                                   80          132.868287
Name: location, dtype: float64

In [20]:
curve_990 = curves[curves['id'] == 990]
curve_990 = curve_990.merge(points, left_index=True, right_index=True)

In [21]:
curve_990_new = data.fit_curve(curve_990)

(array([], dtype=int64),)

/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/psignifit/likelihood.py:191: RuntimeWarning: divide by zero encountered in log
  pbin = pbin  + (ni-ki)*np.log(1-psi)

In [48]:
df = curve_990_new.reset_index(level=[-1, -2])
df = df[~df.index.duplicated()]

In [48]:
curves.loc[curves['id'] == 990, 'location'] = df['location']
curves.loc[curves['id'] == 990, 'width'] = df['width']
curves.loc[curves['id'] == 990, 'gamma'] = df['gamma']
curves.loc[curves['id'] == 990, 'lambda'] = df['lambda']
curves.loc[curves['id'] == 990, 'location_CI_95'] = df['location_CI_95']
curves.loc[curves['id'] == 990, 'width_CI_95'] = df['width_CI_95']
curves.loc[curves['id'] == 990, 'gamma_CI_95'] = df['gamma_CI_95']
curves.loc[curves['id'] == 990, 'lambda_CI_95'] = df['lambda_CI_95']
curves[curves['id'] == 990]

KeyError: ('Z', '2017-01-20', 0, 0, 0, 0, 15, 32)

In [31]:
fitted_curves_copy = fitted_curves
fitted_curves_copy.drop_duplicates(subset=curve_columns + ['base'], inplace=True)

In [34]:
fitted_curves_copy[curve_columns + curve_calculated_columns]

,Monkey,Date,Ref Amp,Ref PW,Ref Freq,Ref Dur,Active Channels,Return Channels,FAs,CRs,...,location_CI_95,width_CI_95,lambda_CI_95,gamma_CI_95,beta_CI_95,location_CI_5,width_CI_5,lambda_CI_5,gamma_CI_5,beta_CI_5
0,U,20160926,0,0,0,0,8,128,8,189,...,786.382167,507.116504,0.004255,0.005121,0.006965,1274.764314,2461.477576,0.199721,0.266349,0.368554
20,U,20160927,0,0,0,0,9,144,37,191,...,850.784753,563.004764,0.009054,0.029938,0.001704,1339.725481,1852.611993,0.265826,0.393491,0.170536
28,U,20160928,0,0,0,0,8,128,37,201,...,819.201226,501.302056,0.015430,0.007456,0.001905,1081.096471,1573.931481,0.155874,0.234235,0.201022
37,U,20160929,0,0,0,0,15,128,83,246,...,811.465608,628.348773,0.001393,0.045894,0.002259,1093.323336,1621.918867,0.098186,0.299524,0.221197
46,U,20161003,0,0,0,0,15,64,11,295,...,770.876373,392.991960,0.000444,0.001699,0.002142,906.398174,883.176659,0.043664,0.121868,0.251619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8020,Z,20170119,0,0,0,0,15,128,34,476,...,22.097915,12.407337,0.009308,0.000906,0.011587,29.691813,32.254696,0.066511,0.138034,0.524543
8028,Z,20170120,0,0,0,0,15,16,21,113,...,57.784375,13.705709,0.010574,0.031409,0.003131,72.277978,67.303253,0.111637,0.321256,0.336625
8036,Z,20170120,0,0,0,0,15,32,18,339,...,56.574764,17.435473,0.003409,0.017295,0.449952,162.743213,282.620962,0.407024,0.281223,0.708815
8048,Z,20170120,0,0,0,0,15,64,5,129,...,39.339222,50.805831,0.001000,0.002636,0.005073,66.909269,147.123905,0.132374,0.202644,0.455702
8060,Z,20170120,0,0,0,0,15,128,15,222,...,23.428511,23.839920,0.000425,0.003285,0.087866,44.528293,97.302562,0.061936,0.219204,0.540514

In [35]:
fitted_curves_copy.to_csv('../data/2-calculated/curves2.csv', index=False)

In [57]:
curves = data.add_relative_errors(curves)
# curves['Channel(s)'], curves['Return Channel(s)'] = curves['Return Channel(s)'], curves['Channel(s)'].copy()

In [60]:
curves.to_hdf('../data/2-calculated.h5', 'curves')
# curves.to_csv('../data/2-calculated/curves2.csv', index=False)

/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Return Channels'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Active Channels'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Dur'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Freq'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Ref PW'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Amp'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Return Channels_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Return Channels_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Return Channels_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Active Channels_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Active Channels_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Active Channels_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Dur_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Dur_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Dur_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Freq_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Freq_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Freq_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref PW_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref PW_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref PW_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Amp_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Amp_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/tyler/.cache/pypoetry/virtualenvs/psychoanalyze-Jj9wTL_R-py3.8/lib/python3.8/site-packages/tables/attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'Ref Amp_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

In [12]:
distal_group = [
    '1','2','3','4','1+2','2+3','3+4','1+4',
    '1+2+3','2+3+4','1+3+4','1+2+4', 
    '1+2+3+4',
]
proximal_group = [
    '5','6','7','8','5+6','6+7','7+8','5+8',
    '5+6+7','6+7+8','5+7+8','5+6+8','5+6+7+8'
]

In [13]:
curves.loc[curves['Channel(s)'].isin(distal_group) & curves['Return Channel(s)'].isin(distal_group), 'Electrode Config'] = 'Multipolar'
curves.loc[curves['Channel(s)'].isin(proximal_group) & curves['Return Channel(s)'].isin(proximal_group), 'Electrode Config'] = 'Multipolar'
curves.loc[curves['Channel(s)'].isin(proximal_group) & curves['Return Channel(s)'].isin(distal_group), 'Electrode Config'] = 'Monopolar'
curves.loc[curves['Channel(s)'].isin(distal_group) & curves['Return Channel(s)'].isin(proximal_group), 'Electrode Config'] = 'Monopolar'

In [14]:
curves['Electrode Config'].value_counts()

Monopolar     890
Multipolar     99
Name: Electrode Config, dtype: int64

In [ ]:
min_max = curves_points.groupby(curves.index.names)['x'].agg(['min', 'max'])
curves = curves.merge(min_max, left_index=True, right_index=True)

In [15]:
curves.to_csv('../data/2-calculated/curves2.csv', index=False)

In [16]:
impedances = pd.read_csv('../data/0-raw/impedances.csv', parse_dates=['Date'])

,Date,Monkey,1,2,3,4,5,6,7,8
0,2016-04-28,Y,NaN,5600.000000,6000.00000,9100.00000,7600.00000,6900.00000,6300.0000,9900.00000
1,2016-05-25,Y,7200.000,6900.000000,7900.00000,9100.00000,7200.00000,7900.00000,6800.0000,7900.00000
2,2016-07-06,Y,10500.000,9900.000000,9900.00000,11700.00000,9200.00000,9500.00000,8100.0000,11500.00000
3,2016-07-26,U,13100.000,11400.000000,16600.00000,12600.00000,13500.00000,11500.00000,15500.0000,15100.00000
4,2018-06-13,U,NaN,22508.300000,6702.55600,9556.43800,5271.66200,6580.15880,3365.4093,3239.66000
5,2017-11-13,Y,NaN,9644.653394,12150.25543,11547.22929,13951.46332,20559.57961,149280.0228,41169.91672
6,2018-01-11,Y,NaN,100745.100000,6948.06600,17257.27000,9591.58400,8436.94900,62547.9900,23621.70000
7,2017-12-13,Y,5534.753,NaN,6152.94100,17821.50000,11496.50000,9295.20300,71058.9100,97559.07000
8,2017-02-11,U,4820.000,12895.000000,6108.00000,6392.00000,8466.00000,5977.00000,6537.0000,6564.00000
9,2016-12-13,U,7514.000,11215.690000,15394.12000,13653.45000,6392.52200,11000.60000,19097.1300,9136.84700
10,2016-12-12,Y,8300.000,8860.500000,7657.50000,7745.00000,9704.00000,9062.50000,7123.5000,8445.50000
11,2017-02-10,Y,9677.000,9750.000000,6944.00000,9257.00000,11991.00000,10899.00000,8078.0000,30950.00000
12,2016-10-21,Z,10248.000,8677.000000,11327.00000,11165.00000,10932.00000,11853.00000,13339.0000,9982.00000
13,2016-12-12,Z,12480.000,9955.000000,12117.00000,12728.00000,20130.00000,14325.00000,17212.0000,17385.00000
14,2016-09-15,Z,3330.000,2589.000000,2760.00000,3131.00000,3495.00000,2667.00000,2403.0000,2453.00000
15,2016-06-23,U,2232.000,2619.000000,1915.00000,1571.00000,2038.00000,2405.00000,2552.0000,2531.00000
16,2016-03-10,Y,937.000,966.000000,1235.00000,690.00000,1267.00000,1309.00000,963.0000,1312.00000

In [21]:
impedances = impedances.merge(monkeys[['Monkey', 'Date of Implant Surgery']])
impedances['Days'] = (impedances['Date'] - impedances['Date of Implant Surgery']).dt.days
impedances = impedances.drop(columns='Date of Implant Surgery')

In [22]:
impedances

    Monkey       Date Channel  1 KHz Impedance  Days
0        Y 2016-04-28       1              NaN    48
1        Y 2016-05-25       1           7200.0    75
2        Y 2016-07-06       1          10500.0   117
3        Y 2017-11-13       1              NaN   612
4        Y 2018-01-11       1              NaN   671
..     ...        ...     ...              ...   ...
131      Z 2016-12-12       7          17212.0    87
132      Z 2016-09-15       7           2403.0    -1
133      Z 2016-10-21       8           9982.0    35
134      Z 2016-12-12       8          17385.0    87
135      Z 2016-09-15       8           2453.0    -1

[136 rows x 5 columns]

In [23]:
impedances.to_csv('../data/2-calculated/impedances.csv', index=False)

In [28]:
pd.read_csv('../data/2-calculated/curves2.csv').drop(columns='Unnamed: 0').to_csv('../data/2-calculated/curves2.csv', index=False)

In [6]:
points = pd.read_hdf('../data/2-calculated.h5', 'points')
points['Ref Current'] = points.index.get_level_values('Ref Amp')*points.index.get_level_values['Ref PW']
points['Comp Current'] = points.index.get_level_values['Comp Amp']*points.index.get_level_values['Comp PW']

TypeError: 'method' object is not subscriptable

In [23]:
curves = data.load('curves', outliers=None)

In [24]:
curves['Ref Current'] = curves.index.get_level_values('Ref Amp') * curves.index.get_level_values('Ref PW') / 1000
curves['Ref Current']

Monkey  Date        Ref Amp  Ref PW  Ref Freq  Ref Dur  Active Channels  Return Channels
U       2016-09-27  0        0       0         0        9                144                0.0
        2016-09-28  0        0       0         0        8                128                0.0
        2016-09-29  0        0       0         0        15               128                0.0
        2016-10-03  0        0       0         0        15               64                 0.0
        2016-10-05  0        0       0         0        240              4                  0.0
                                                                                           ...
Z       2017-01-19  0        0       0         0        15               128                0.0
        2017-01-20  0        0       0         0        15               16                 0.0
                                                                         32                 0.0
                                                                         64                 0.0
                                                                         128                0.0
Name: Ref Current, Length: 863, dtype: float64

In [25]:
curves.to_hdf('../data/2-calculated.h5', 'curves')

In [18]:
points = data.load('points', outliers=None)

In [19]:
points['Comp Current'] = points.index.get_level_values('Comp Amp') * points.index.get_level_values('Comp PW') / 1000
points.to_hdf('../data/2-calculated.h5', 'points')

In [ ]:
points.to_hdf('../data/1-normalized.h5', 'points')
sessions.to_hdf('../data/1-normalized.h5', 'sessions')
monkeys.to_hdf('../data/1-normalized.h5', 'monkeys')